# Generated by Django 5.2.3 on 2025-07-12 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_basic_salary_customuser_philhealth_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('clerk', 'Clerk'), ('technician', 'Technician')], max_length=20),
        ),
    ]
