# Generated by Django 5.2.3 on 2026-02-07 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_add_birthday_greeting_variant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='has_government_benefits',
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_bir_tax',
            field=models.BooleanField(default=True, help_text='Apply BIR withholding tax deductions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_pagibig',
            field=models.BooleanField(default=True, help_text='Apply Pag-IBIG (HDMF) deductions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_philhealth',
            field=models.BooleanField(default=True, help_text='Apply PhilHealth deductions'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='has_sss',
            field=models.BooleanField(default=True, help_text='Apply SSS (Social Security System) deductions'),
        ),
    ]
