# Generated by Django 5.2.3 on 2026-02-07 11:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_customuser_has_government_benefits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cash_ban_balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Employee's cash ban fund balance (accumulated fund that can be received at year-end or cash advanced)", max_digits=10),
        ),
        migrations.CreateModel(
            name='CashAdvance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount of cash advance taken from cash ban balance', max_digits=10)),
                ('date', models.DateField(help_text='Date when cash advance was given')),
                ('reason', models.TextField(blank=True, help_text='Reason or notes for the cash advance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(help_text='User who approved/recorded this cash advance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_advances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(help_text='Employee who took the cash advance', on_delete=django.db.models.deletion.CASCADE, related_name='cash_advances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'date'], name='users_casha_employe_829781_idx'), models.Index(fields=['-date'], name='users_casha_date_5c3913_idx')],
            },
        ),
    ]
