# Generated by Django 5.2.3 on 2026-02-07 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_customuser_cash_ban_balance_cashadvance'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='has_cash_ban',
            field=models.BooleanField(default=True, help_text='Include employee in cash ban fund contributions'),
        ),
    ]
