# Generated by Django 5.2.3 on 2026-02-14 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_cashadvancemovement_delete_cashadvance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='cashadvancemovement',
            new_name='users_casha_employe_944da5_idx',
            old_name='users_cashad_employe_idx',
        ),
        migrations.RenameIndex(
            model_name='cashadvancemovement',
            new_name='users_casha_date_616bbe_idx',
            old_name='users_cashad_date_idx',
        ),
        migrations.RenameIndex(
            model_name='cashadvancemovement',
            new_name='users_casha_employe_f5a4fb_idx',
            old_name='users_cashad_emp_type_idx',
        ),
        migrations.AddField(
            model_name='cashadvancemovement',
            name='is_pending',
            field=models.BooleanField(default=False, help_text='If True, movement is pending (linked to draft payroll) and not yet applied to balance'),
        ),
        migrations.AlterField(
            model_name='cashadvancemovement',
            name='description',
            field=models.TextField(blank=True, help_text="Notes or reason for the movement (e.g., 'Initial cash ban balance', 'Cash advance for personal use')"),
        ),
    ]
