# Generated by Django 5.2.3 on 2026-07-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_systemsettings_google_sheets_share_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsettings',
            name='google_sheets_spreadsheet_id',
            field=models.CharField(blank=True, default='', help_text='Sub-stall monthly Google Spreadsheet ID from the sheet URL', max_length=255),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='google_sheets_sub_stall_type',
            field=models.CharField(blank=True, default='sub', help_text='Manual sync scope: sub, main, or both', max_length=10),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='google_sheets_sync_enabled',
            field=models.BooleanField(default=False, help_text='Enable automatic sync of daily sales/remittance summaries to Google Sheets'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='google_sheets_worksheet_name',
            field=models.CharField(blank=True, default='Sub Stall Sales', help_text='Legacy worksheet name (daily tabs are auto-generated)', max_length=100),
        ),
    ]
