services:
  api:
    build:
      context: .
      target: development
    env_file:
      - .env.local
    environment:
      DJANGO_ENV_FILE: .env.local
    command: python manage.py runserver 0.0.0.0:56001
    volumes:
      - .:/usr/src/app
    ports:
      - "56001:56001"

  celery:
    build:
      context: .
      target: development
    env_file:
      - .env.local
    environment:
      DJANGO_ENV_FILE: .env.local
    command: celery -A config worker -l info
    volumes:
      - .:/usr/src/app

  celery-beat:
    build:
      context: .
      target: development
    env_file:
      - .env.local
    environment:
      DJANGO_ENV_FILE: .env.local
    command: celery -A config beat -l info
    volumes:
      - .:/usr/src/app

  db:
    env_file:
      - .env.local
    ports:
      - "5432:5432"
