services:
    db:
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U $DB_USER -d $DB_NAME"]
            interval: 10s
            timeout: 5s
            retries: 5

    api:
        image: rnldvrgl/rvdc_backend:latest
        depends_on:
            db:
                condition: service_healthy
        ports:
            - "8000:8000"
        volumes:
            - /srv/rvdc_backend/media:/app/media  # Map media files to host
            - /srv/rvdc_backend/staticfiles:/app/staticfiles  # Map static files to host

volumes:
    postgres_data:
