version: "3.9"

services:
    api:
        image: rnldvrgl/rvdc_backend:latest
        env_file:
            - .env.production
        command:
            [
                "gunicorn",
                "config.wsgi:application",
                "--bind",
                "0.0.0.0:8000",
                "--workers",
                "2",
                "--threads",
                "2",
                "--timeout",
                "60",
            ]
        volumes:
            - ./staticfiles:/usr/src/app/staticfiles
            - ./media:/usr/src/app/media
        ports:
            - "8000:8000"
        depends_on:
            - db

    db:
        image: postgres:16
        env_file:
            - .env.production
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
    staticfiles:
    media:
