services:
    api:
        build:
            context: .
            target: development
        env_file:
            - .env.local
        command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]

    db:
        env_file:
            - .env.local
        ports:
            - "5432:5432"
