# Generated by Django 5.2.3 on 2026-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_event_d_52e5bf_idx',
            old_name='calendar_ev_event_d_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_event_t_25cdb4_idx',
            old_name='calendar_ev_event_t_idx',
        ),
        migrations.RenameIndex(
            model_name='calendarevent',
            new_name='calendar_ev_is_dele_5384d9_idx',
            old_name='calendar_ev_is_dele_idx',
        ),
        migrations.AlterField(
            model_name='calendarevent',
            name='event_type',
            field=models.CharField(choices=[('meeting', 'Meeting'), ('maintenance', 'Maintenance'), ('training', 'Training'), ('deadline', 'Deadline'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
