# Generated by Django 5.2.3 on 2025-07-09 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_expense_is_closed_expense_paid_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='is_closed',
            new_name='is_paid',
        ),
    ]
