# Generated by Django 5.2.3 on 2025-07-18 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_rename_is_closed_expense_is_paid'),
        ('inventory', '0028_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='inventory.stall'),
        ),
    ]
