# Generated by Django 5.2.3 on 2025-07-25 06:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0005_alter_expense_stall'),
        ('inventory', '0029_item_cost_price_item_technician_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='transfer',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='expense', to='inventory.stocktransfer'),
            preserve_default=False,
        ),
    ]
