# Generated by Django 5.2.3 on 2026-02-01 03:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0008_add_expense_categories_and_workflow'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-expense_date', '-created_at'], 'verbose_name': 'Expense', 'verbose_name_plural': 'Expenses'},
        ),
        migrations.AlterModelOptions(
            name='expenseitem',
            options={'ordering': ['id'], 'verbose_name': 'Expense Item', 'verbose_name_plural': 'Expense Items'},
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_stall_i_8f5138_idx',
            old_name='expenses_ex_stall_i_a1b2c3_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_categor_6b4e94_idx',
            old_name='expenses_ex_categor_d4e5f6_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_payment_98443f_idx',
            old_name='expenses_ex_payment_j1k2l3_idx',
        ),
        migrations.RenameIndex(
            model_name='expense',
            new_name='expenses_ex_is_dele_bb1e13_idx',
            old_name='expenses_ex_is_dele_m4n5o6_idx',
        ),
        migrations.RenameIndex(
            model_name='expensecategory',
            new_name='expenses_ex_is_acti_2bfc8c_idx',
            old_name='expenses_ex_is_acti_8b5c3f_idx',
        ),
        migrations.AddField(
            model_name='expense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual'), ('service', 'Service')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='expenseitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
