# Generated by Django 5.2.3 on 2026-02-01 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0009_alter_expense_options_alter_expenseitem_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='payment_method',
            field=models.CharField(blank=True, default='cash', help_text='Cash, Bank Transfer, Cheque, etc.', max_length=50),
        ),
    ]
