# Generated by Django 5.2.3 on 2025-08-17 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_client_is_blocklisted'),
        ('inventory', '0030_stock_track_stock'),
        ('sales', '0008_salestransaction_change_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Appliance Type',
                'verbose_name_plural': 'Appliance Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('repair', 'Repair'), ('installation', 'Installation'), ('motor_rewind', 'Motor Rewind'), ('check_up', 'Check-up'), ('cleaning', 'Cleaning')], max_length=30)),
                ('service_mode', models.CharField(choices=[('in_shop', 'In-Shop'), ('home_service', 'Home Service'), ('pull_out_return', 'Pull-Out & Return')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('override_address', models.TextField(blank=True, null=True)),
                ('override_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('override_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('estimated_duration', models.PositiveIntegerField(default=60)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Waiting for Parts)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='clients.client')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salestransaction')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_reported', models.TextField(blank=True, null=True)),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('waiting_parts', 'Waiting for Parts'), ('under_repair', 'Under Repair'), ('fixed', 'Fixed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('labor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appliance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_appliances', to='services.appliancetype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='services.service')),
            ],
            options={
                'ordering': ['appliance_type__name', 'brand'],
            },
        ),
        migrations.CreateModel(
            name='ApplianceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('waiting_parts', 'Waiting for Parts'), ('under_repair', 'Under Repair'), ('fixed', 'Fixed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.serviceappliance')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplianceItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='services.serviceappliance')),
            ],
            options={
                'verbose_name': 'Appliance Item Used',
                'verbose_name_plural': 'Appliance Items Used',
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Waiting for Parts)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.service')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='technician_assignments', to='services.serviceappliance')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_assignments', to='services.service')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Technician Assignment',
                'verbose_name_plural': 'Technician Assignments',
            },
        ),
    ]
