# Generated by Django 5.2.3 on 2025-06-26 06:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0006_stock_low_stock_threshold_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appliance_type', models.CharField(choices=[('aircon', 'Air Conditioner'), ('fan', 'Electric Fan'), ('ref', 'Refrigerator'), ('washing_machine', 'Washing Machine'), ('water_dispenser', 'Water Dispenser'), ('microwave', 'Microwave'), ('freezer', 'Freezer')], max_length=30)),
                ('brand', models.CharField(max_length=100)),
                ('unit_type', models.CharField(max_length=100)),
                ('service_type', models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('dismantle_reinstall', 'Dismantle & Reinstall'), ('dismantle', 'Dismantle Only'), ('checkup', 'Check-up / Diagnosis'), ('maintenance', 'Preventive Maintenance'), ('reinstallation', 'Reinstallation'), ('rewind', 'Rewinding Motor'), ('reprocess', 'Reprocessing Refrigerant')], max_length=30)),
                ('previous_service_type', models.CharField(blank=True, choices=[('installation', 'Installation'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('dismantle_reinstall', 'Dismantle & Reinstall'), ('dismantle', 'Dismantle Only'), ('checkup', 'Check-up / Diagnosis'), ('maintenance', 'Preventive Maintenance'), ('reinstallation', 'Reinstallation'), ('rewind', 'Rewinding Motor'), ('reprocess', 'Reprocessing Refrigerant')], max_length=30, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('done', 'Completed'), ('picked_up', 'Picked Up'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('date_received', models.DateTimeField(auto_now_add=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('technicians', models.ManyToManyField(related_name='service_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.PositiveIntegerField()),
                ('deducted_at', models.DateTimeField(auto_now_add=True)),
                ('deducted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='item_deductions', to=settings.AUTH_USER_MODEL)),
                ('deducted_from_stall', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.stall')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_items', to='services.servicerequest')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('installation', 'Installation'), ('repair', 'Repair'), ('cleaning', 'Cleaning'), ('dismantle_reinstall', 'Dismantle & Reinstall'), ('dismantle', 'Dismantle Only'), ('checkup', 'Check-up / Diagnosis'), ('maintenance', 'Preventive Maintenance'), ('reinstallation', 'Reinstallation'), ('rewind', 'Rewinding Motor'), ('reprocess', 'Reprocessing Refrigerant')], max_length=30)),
                ('performed_on', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('service_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.servicerequest')),
            ],
        ),
    ]
