# Generated by Django 5.2.3 on 2025-07-30 09:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_add_partial_unique_index'),
        ('inventory', '0029_item_cost_price_item_technician_price_and_more'),
        ('sales', '0008_salestransaction_change_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('repair', 'Repair'), ('installation', 'Installation'), ('motor_rewind', 'Motor Rewind'), ('check_up', 'Check-up'), ('cleaning', 'Cleaning')], max_length=30)),
                ('service_mode', models.CharField(choices=[('in_shop', 'In-Shop'), ('home_service', 'Home Service'), ('pickup', 'Pickup and Return')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('override_address', models.TextField(blank=True, null=True)),
                ('override_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('override_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('pickup_date', models.DateField(blank=True, null=True)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Waiting for Parts)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salestransaction')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_reported', models.TextField(blank=True, null=True)),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('waiting_parts', 'Waiting for Parts'), ('under_repair', 'Under Repair'), ('fixed', 'Fixed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('labor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appliance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_services', to='services.appliancetype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='services.serviceappliance')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('waiting_parts', 'Waiting for Parts'), ('under_repair', 'Under Repair'), ('fixed', 'Fixed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliance_status_history', to='services.serviceappliance')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='services.serviceappliance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Waiting for Parts)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_status_history', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceTechnician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technicians', to='services.service')),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TechnicianAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_start', models.TimeField()),
                ('time_end', models.TimeField()),
                ('is_available', models.BooleanField(default=True)),
                ('technician', models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('technician', 'date', 'time_start', 'time_end')},
            },
        ),
    ]
