# Generated by Django 5.2.3 on 2025-06-26 04:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_servicerequestitem_deducted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='technician',
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='technicians',
            field=models.ManyToManyField(related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
