# Generated by Django 5.2.3 on 2025-07-28 07:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_partial_unique_index'),
        ('inventory', '0029_item_cost_price_item_technician_price_and_more'),
        ('sales', '0009_salesitem_aircon_unit'),
        ('services', '0002_servicerequest_final_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirconInstallation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('inventory', 'From Inventory'), ('client_provided', 'Client Provided')], max_length=30)),
            ],
            options={
                'verbose_name': 'Aircon Installation',
                'verbose_name_plural': 'Aircon Installations',
            },
        ),
        migrations.CreateModel(
            name='ApplianceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='client',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='sales_transaction',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='technicians',
        ),
        migrations.RemoveField(
            model_name='servicerequestitem',
            name='service_request',
        ),
        migrations.RemoveField(
            model_name='servicerequestitem',
            name='deducted_by',
        ),
        migrations.RemoveField(
            model_name='servicerequestitem',
            name='deducted_from_stall',
        ),
        migrations.RemoveField(
            model_name='servicerequestitem',
            name='item',
        ),
        migrations.CreateModel(
            name='AirconItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity_used', models.PositiveIntegerField()),
                ('free_quantity', models.PositiveIntegerField(default=0)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='services.airconinstallation')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
            ],
            options={
                'verbose_name': 'Aircon Item Used',
                'verbose_name_plural': 'Aircon Items Used',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service_type', models.CharField(choices=[('repair', 'Repair'), ('installation', 'Installation'), ('motor_rewind', 'Motor Rewind'), ('check_up', 'Check-up'), ('cleaning', 'Cleaning')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Waiting for Parts)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='in_progress', max_length=30)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.client')),
                ('related_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salestransaction')),
            ],
        ),
        migrations.CreateModel(
            name='MotorRewind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('labor_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appliance_type', models.ForeignKey(help_text='Type of motor (e.g., Electric Fan, Aircon Compressor)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.appliancetype')),
                ('related_transaction', models.ForeignKey(blank=True, help_text='Optional transaction for billing this motor rewind', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.salestransaction')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='motor_rewinds', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='HomeServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateField()),
                ('scheduled_time', models.TimeField(blank=True, null=True)),
                ('override_address', models.TextField(blank=True, null=True)),
                ('override_contact_person', models.CharField(blank=True, max_length=100, null=True)),
                ('override_contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='home_service_schedule', to='services.service')),
            ],
        ),
        migrations.AddField(
            model_name='airconinstallation',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aircon_installation', to='services.service'),
        ),
        migrations.CreateModel(
            name='ServiceAppliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_reported', models.TextField(blank=True, null=True)),
                ('diagnosis_notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('waiting_parts', 'Waiting for Parts'), ('under_repair', 'Under Repair'), ('fixed', 'Fixed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='received', max_length=20)),
                ('labor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('appliance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_in_services', to='services.appliancetype')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='services.service')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('waiting_parts', 'Waiting for Parts'), ('under_repair', 'Under Repair'), ('fixed', 'Fixed'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.serviceappliance')),
            ],
        ),
        migrations.CreateModel(
            name='ApplianceItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='services.serviceappliance')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('on_hold', 'On Hold (Waiting for Parts)'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=30)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='services.service')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceStep',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
        migrations.DeleteModel(
            name='ServiceRequestItem',
        ),
    ]
