# Generated by Django 5.2.3 on 2025-12-04 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_alter_expense_transfer'),
        ('inventory', '0034_stall_inventory_enabled_stall_is_system'),
        ('services', '0010_free_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceitemused',
            name='expense',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items', to='expenses.expense'),
        ),
        migrations.AddField(
            model_name='applianceitemused',
            name='stall_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appliance_items_used', to='inventory.stock'),
        ),
        migrations.AddField(
            model_name='service',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='inventory.stall'),
        ),
        migrations.AddField(
            model_name='technicianassignment',
            name='assignment_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('pickup', 'Pick-up (Pull-Out)'), ('delivery', 'Delivery/Return'), ('inspect', 'Inspect/On-site')], default='repair', max_length=20),
        ),
        migrations.AddField(
            model_name='technicianassignment',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
