# Generated by Django 5.2.3 on 2026-02-01 09:14

from django.db import migrations


def update_service_type_enums(apps, schema_editor):
    """Update CHECK_UP to INSPECTION in Service and related models"""
    Service = apps.get_model('services', 'Service')

    # Update Service records
    Service.objects.filter(service_type='check_up').update(service_type='inspection')

    # Note: WarrantyClaim validation references ServiceType.CHECK_UP
    # This will be handled by code changes, not data migration


def update_service_mode_enums(apps, schema_editor):
    """Update IN_SHOP to CARRY_IN and PULL_OUT_RETURN to PULL_OUT"""
    Service = apps.get_model('services', 'Service')

    # Update service mode values
    Service.objects.filter(service_mode='in_shop').update(service_mode='carry_in')
    Service.objects.filter(service_mode='pull_out_return').update(service_mode='pull_out')


def reverse_service_type_enums(apps, schema_editor):
    """Reverse: INSPECTION back to CHECK_UP"""
    Service = apps.get_model('services', 'Service')
    Service.objects.filter(service_type='inspection').update(service_type='check_up')


def reverse_service_mode_enums(apps, schema_editor):
    """Reverse: CARRY_IN back to IN_SHOP, PULL_OUT back to PULL_OUT_RETURN"""
    Service = apps.get_model('services', 'Service')
    Service.objects.filter(service_mode='carry_in').update(service_mode='in_shop')
    Service.objects.filter(service_mode='pull_out').update(service_mode='pull_out_return')


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_add_service_payment_tracking'),
    ]

    operations = [
        migrations.RunPython(
            update_service_type_enums,
            reverse_service_type_enums
        ),
        migrations.RunPython(
            update_service_mode_enums,
            reverse_service_mode_enums
        ),
    ]
