# Generated by Django 5.2.3 on 2026-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_update_service_enums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='service_mode',
            field=models.CharField(choices=[('carry_in', 'Carry-In'), ('home_service', 'Home Service'), ('pull_out', 'Pull-Out')], max_length=30),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('installation', 'Installation'), ('motor_rewind', 'Motor Rewind'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning')], max_length=30),
        ),
    ]
