# Generated by Django 5.2.3 on 2026-02-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_remove_scheduling_fields_add_validation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='estimated_duration',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='service',
            name='scheduled_time',
        ),
        migrations.AddField(
            model_name='service',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='When customer dropped off unit (carry-in services)', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Delivery date for pull-out services (set when scheduling delivery after repair)', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='pickup_date',
            field=models.DateField(blank=True, help_text='Pickup date for pull-out services (set at service creation)', null=True),
        ),
    ]
