# Generated by Django 5.2.3 on 2026-02-01 10:00

from django.db import migrations, models


def migrate_appliance_status(apps, schema_editor):
    """Migrate old appliance status values to new ones"""
    ServiceAppliance = apps.get_model('services', 'ServiceAppliance')
    
    # Map old status values to new ones
    status_mapping = {
        'waiting_parts': 'in_repair',      # Waiting for parts -> In Repair
        'under_repair': 'in_repair',       # Under Repair -> In Repair
        'fixed': 'completed',              # Fixed -> Completed
        'cancelled': 'delivered',          # Cancelled -> Delivered (or consider separate handling)
    }
    
    for old_status, new_status in status_mapping.items():
        ServiceAppliance.objects.filter(status=old_status).update(status=new_status)
    
    # Also migrate ApplianceStatusHistory if it exists
    ApplianceStatusHistory = apps.get_model('services', 'ApplianceStatusHistory')
    for old_status, new_status in status_mapping.items():
        ApplianceStatusHistory.objects.filter(status=old_status).update(status=new_status)


def reverse_appliance_status(apps, schema_editor):
    """Reverse the migration"""
    ServiceAppliance = apps.get_model('services', 'ServiceAppliance')
    ApplianceStatusHistory = apps.get_model('services', 'ApplianceStatusHistory')
    
    # Reverse mapping
    reverse_mapping = {
        'in_repair': 'under_repair',
        'completed': 'fixed',
        'delivered': 'cancelled',
    }
    
    for new_status, old_status in reverse_mapping.items():
        ServiceAppliance.objects.filter(status=new_status).update(status=old_status)
        ApplianceStatusHistory.objects.filter(status=new_status).update(status=old_status)


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_remove_scheduling_fields'),
    ]

    operations = [
        migrations.RunPython(
            migrate_appliance_status,
            reverse_appliance_status
        ),
        migrations.AlterField(
            model_name='serviceappliance',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'Received'),
                    ('diagnosed', 'Diagnosed'),
                    ('in_repair', 'In Repair'),
                    ('completed', 'Completed'),
                    ('ready_for_pickup', 'Ready for Pickup'),
                    ('delivered', 'Delivered'),
                ],
                default='received',
                max_length=20
            ),
        ),
        migrations.AlterField(
            model_name='appliancestatushistory',
            name='status',
            field=models.CharField(
                choices=[
                    ('received', 'Received'),
                    ('diagnosed', 'Diagnosed'),
                    ('in_repair', 'In Repair'),
                    ('completed', 'Completed'),
                    ('ready_for_pickup', 'Ready for Pickup'),
                    ('delivered', 'Delivered'),
                ],
                max_length=30
            ),
        ),
    ]
