# Generated by Django 5.2.3 on 2026-02-01 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0017_update_appliance_status_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceitemused',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applianceitemused',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount for this item', max_digits=10),
        ),
        migrations.AddField(
            model_name='applianceitemused',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (0.00 - 100.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='applianceitemused',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Reason for item discount', max_length=200),
        ),
        migrations.AddField(
            model_name='applianceitemused',
            name='is_cancelled',
            field=models.BooleanField(default=False, help_text='True if service was cancelled and part returned to stock'),
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_date',
            field=models.DateTimeField(blank=True, help_text='When service was cancelled', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_reason',
            field=models.TextField(blank=True, help_text='Reason for service cancellation', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_reason',
            field=models.CharField(blank=True, help_text="Reason for discount (e.g., 'Senior Citizen', 'Loyalty Discount')", max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='last_refund_date',
            field=models.DateTimeField(blank=True, help_text='Date of most recent refund', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount for entire service', max_digits=10),
        ),
        migrations.AddField(
            model_name='service',
            name='service_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount for entire service (0.00 - 100.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='service',
            name='total_refunded',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount refunded for this completed service', max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, help_text='Technician assigned to work on this appliance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_appliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='labor_discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount for labor', max_digits=10),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='labor_discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount for labor (0.00 - 100.00)', max_digits=5),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='labor_discount_reason',
            field=models.CharField(blank=True, help_text='Reason for labor discount', max_length=200),
        ),
        migrations.CreateModel(
            name='ServiceRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_amount', models.DecimalField(decimal_places=2, help_text='Amount refunded', max_digits=10)),
                ('refund_type', models.CharField(choices=[('full', 'Full Refund'), ('partial', 'Partial Refund')], default='partial', max_length=10)),
                ('reason', models.TextField(help_text='Reason for refund')),
                ('refund_date', models.DateTimeField(auto_now_add=True)),
                ('refund_method', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('bank_transfer', 'Bank Transfer')], default='cash', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_processed', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='services.service')),
            ],
            options={
                'verbose_name': 'Service Refund',
                'verbose_name_plural': 'Service Refunds',
                'ordering': ['-refund_date'],
            },
        ),
    ]
