# Generated by Django 5.2.3 on 2026-02-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0018_applianceitemused_cancelled_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='delivery_date',
            field=models.DateTimeField(blank=True, help_text='Delivery date and time for pull-out services (set when scheduling delivery after repair)', null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='pickup_date',
            field=models.DateTimeField(blank=True, help_text='Pickup date and time for pull-out services (set at service creation)', null=True),
        ),
    ]
