# Generated by Django 5.2.3 on 2026-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0019_alter_service_delivery_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='complementary_reason',
            field=models.CharField(blank=True, help_text="Reason for complementary service (e.g., 'Warranty', 'Goodwill', 'Promotional')", max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='is_complementary',
            field=models.BooleanField(default=False, help_text='Mark as complementary for free services (warranty, goodwill, promotional)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('n/a', 'N/A (Complementary)')], default='unpaid', help_text='Payment status of this service', max_length=10),
        ),
    ]
