# Generated by Django 5.2.3 on 2026-02-10 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0020_service_complementary_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappliance',
            name='serial_number',
            field=models.CharField(blank=True, help_text='Serial number of the appliance (optional)', max_length=100, null=True),
        ),
    ]
