# Generated by Django 5.2.3 on 2026-02-11 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0021_add_serial_number_to_service_appliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappliance',
            name='labor_warranty_months',
            field=models.PositiveIntegerField(default=0, help_text='Labor warranty period in months (0 = no warranty)'),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='unit_warranty_months',
            field=models.PositiveIntegerField(default=0, help_text='Unit warranty period in months (0 = no warranty)'),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='warranty_notes',
            field=models.TextField(blank=True, help_text='Warranty details and notes (e.g., compressor warranty, parts coverage)'),
        ),
    ]
