# Generated by Django 5.2.3 on 2026-02-11 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0022_serviceappliance_labor_warranty_months_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappliance',
            name='labor_warranty_end_date',
            field=models.DateField(blank=True, help_text='Date when labor warranty expires', null=True),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='unit_warranty_end_date',
            field=models.DateField(blank=True, help_text='Date when unit warranty expires', null=True),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='warranty_start_date',
            field=models.DateField(blank=True, help_text='Date when warranty becomes active (set when installation is completed)', null=True),
        ),
    ]
