# Generated by Django 5.2.3 on 2026-03-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0024_add_unit_price_and_installation_statuses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliancestatushistory',
            name='status',
            field=models.CharField(choices=[('received', 'Received'), ('diagnosed', 'Diagnosed'), ('in_repair', 'In Repair'), ('completed', 'Completed'), ('ready_for_pickup', 'Ready for Pickup'), ('delivered', 'Delivered'), ('reserved', 'Reserved'), ('installed', 'Installed')], max_length=30),
        ),
    ]
