# Generated by Django 5.2.3 on 2026-03-05 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_deleted_at'),
        ('inventory', '0042_decimal_quantities_and_waste_tolerance'),
        ('sales', '0010_add_performance_indexes'),
        ('services', '0027_service_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applianceitemused',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Quantity used (supports decimals for kg, ft, etc.).', max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('repair', 'Repair'), ('dismantle', 'Dismantle'), ('installation', 'Installation'), ('motor_rewind', 'Motor Rewind'), ('inspection', 'Inspection'), ('cleaning', 'Cleaning')], max_length=30),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_deleted'], name='service_is_deleted_idx'),
        ),
    ]
