# Generated by Django 5.2.3 on 2026-03-12 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0012_expensecategory_deleted_at'),
        ('inventory', '0042_decimal_quantities_and_waste_tolerance'),
        ('services', '0030_service_related_sub_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItemUsed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=1, help_text='Quantity used (supports decimals for kg, ft, etc.).', max_digits=10)),
                ('is_free', models.BooleanField(default=False, help_text='Mark this part as free to the customer.')),
                ('free_quantity', models.PositiveIntegerField(default=0, help_text='Quantity given free as part of promotion')),
                ('promo_name', models.CharField(blank=True, help_text='Name of applied promotion', max_length=100)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed discount amount for this item', max_digits=10)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount (0.00 - 100.00)', max_digits=5)),
                ('discount_reason', models.CharField(blank=True, help_text='Reason for item discount', max_length=200)),
                ('is_cancelled', models.BooleanField(default=False, help_text='True if service was cancelled and part returned to stock')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('expense', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_level_items', to='expenses.expense')),
                ('item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='services.service')),
                ('stall_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_items_used', to='inventory.stock')),
            ],
            options={
                'verbose_name': 'Service Item Used',
                'verbose_name_plural': 'Service Items Used',
            },
        ),
    ]
