# Generated by Django 5.2.3 on 2026-03-12 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0031_add_service_item_used'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicestatushistory',
            name='changed_by',
        ),
        migrations.RemoveField(
            model_name='servicestatushistory',
            name='service',
        ),
        migrations.DeleteModel(
            name='ApplianceStatusHistory',
        ),
        migrations.DeleteModel(
            name='ServiceStatusHistory',
        ),
    ]
