# Generated by Django 5.2.3 on 2026-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0032_remove_servicestatushistory_changed_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceitemused',
            name='stock_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Stock Request'), ('approved', 'Stock Request Approved'), ('declined', 'Stock Request Declined')], help_text='Set when item was added with insufficient stock. Null means no stock request needed.', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceitemused',
            name='stock_request_status',
            field=models.CharField(blank=True, choices=[('pending', 'Pending Stock Request'), ('approved', 'Stock Request Approved'), ('declined', 'Stock Request Declined')], help_text='Set when item was added with insufficient stock. Null means no stock request needed.', max_length=10, null=True),
        ),
    ]
