# Generated by Django 5.2.3 on 2026-03-12 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_stockrequest'),
        ('services', '0033_applianceitemused_stock_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applianceitemused',
            name='custom_description',
            field=models.CharField(blank=True, help_text='Description for custom items not in inventory.', max_length=200),
        ),
        migrations.AddField(
            model_name='applianceitemused',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit for custom items not in inventory.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceitemused',
            name='custom_description',
            field=models.CharField(blank=True, help_text='Description for custom items not in inventory.', max_length=200),
        ),
        migrations.AddField(
            model_name='serviceitemused',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price per unit for custom items not in inventory.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='applianceitemused',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='serviceitemused',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
    ]
