# Generated by Django 5.2.3 on 2026-03-13 00:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0034_custom_item_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappliance',
            name='items_checked',
            field=models.BooleanField(default=False, help_text='Whether items/parts have been reviewed and confirmed by clerk'),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='items_checked_at',
            field=models.DateTimeField(blank=True, help_text='When items were confirmed', null=True),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='items_checked_by',
            field=models.ForeignKey(blank=True, help_text='User who confirmed the items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items_checked_appliances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='parts_needed_notes',
            field=models.TextField(blank=True, help_text='Manager/technician notes on what parts are needed (for clerk reference)'),
        ),
    ]
