# Generated by Django 5.2.3 on 2026-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0039_add_with_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='receipt_book',
            field=models.CharField(blank=True, help_text="Receipt book number (e.g. '1', '2'). Same OR # can exist in different books.", max_length=50, null=True),
        ),
    ]
