# Generated by Django 5.2.3 on 2026-03-28 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0049_remove_custom_description_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicereceipt',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount covered by this receipt (optional, for partial-payment tracking).', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='receipt_book',
            field=models.CharField(blank=True, help_text='Receipt book number, used to disambiguate duplicate receipt numbers across books.', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servicereceipt',
            name='with_2307',
            field=models.BooleanField(default=False, help_text='Whether this receipt has an attached BIR Form 2307 (OR only).'),
        ),
        migrations.AlterField(
            model_name='technicianassignment',
            name='technician',
            field=models.ForeignKey(limit_choices_to={'role': 'technician'}, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='JobOrderTemplatePrint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_number', models.PositiveIntegerField()),
                ('end_number', models.PositiveIntegerField()),
                ('printed_at', models.DateTimeField(auto_now_add=True)),
                ('printed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_order_prints', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Job Order Template Print',
                'verbose_name_plural': 'Job Order Template Prints',
                'ordering': ['-printed_at'],
            },
        ),
    ]
