# Generated by Django 5.2.3 on 2026-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0052_appliance_type_warranty_defaults_service_forfeiture_company_asset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyasset',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('n/a', 'N/A (Complementary)'), ('written_off', 'Written Off (Forfeited)')], default='unpaid', help_text='Payment status of this service', max_length=11),
        ),
    ]
