# Generated by Django 5.2.3 on 2026-04-01 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0053_alter_companyasset_id_alter_service_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceappliance',
            name='acquisition_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price agreed upon when the client sells the appliance to the company', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='When this specific appliance was claimed/collected by the client', null=True),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='forfeiture_notes',
            field=models.TextField(blank=True, default='', help_text='Additional notes on the forfeiture / acquisition'),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='forfeiture_type',
            field=models.CharField(blank=True, choices=[('unclaimed', 'Unclaimed'), ('client_sold', 'Client Sold')], help_text='How the appliance became company property', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='serviceappliance',
            name='is_forfeited',
            field=models.BooleanField(default=False, help_text='Whether this appliance has been forfeited or acquired by the company'),
        ),
    ]
