# Generated by Django 5.2.3 on 2026-04-02 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0055_add_pending_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('refunded', 'Refunded'), ('no_charge', 'No Charge'), ('written_off', 'Written Off (Forfeited)')], default='pending', help_text='Payment status of this service', max_length=11),
        ),
    ]
