# Generated by Django 5.2.3 on 2026-04-02 23:27

from decimal import Decimal
from django.db import migrations


def migrate_payment_statuses(apps, schema_editor):
    """
    1. Rename 'n/a' → 'no_charge'
    2. Fix zero-total services that were incorrectly set to 'paid' → 'pending'
    """
    Service = apps.get_model("services", "Service")

    # 1. Convert all 'n/a' to 'no_charge'
    na_count = Service.objects.filter(payment_status="n/a").update(
        payment_status="no_charge"
    )

    # 2. Fix zero-total services marked as 'paid' that have no payments
    #    These were marked 'paid' by the old logic: "if total <= 0 → paid"
    zero_total_paid = Service.objects.filter(
        payment_status="paid",
        total_revenue__lte=Decimal("0"),
        is_complementary=False,
        is_forfeited=False,
    )
    # Only fix ones with no actual payments
    fixed_count = 0
    for svc in zero_total_paid:
        if not svc.payments.exists():
            svc.payment_status = "pending"
            svc.save(update_fields=["payment_status"])
            fixed_count += 1

    if na_count or fixed_count:
        print(
            f"\n  Migrated {na_count} services from 'n/a' → 'no_charge', "
            f"fixed {fixed_count} zero-total services from 'paid' → 'pending'"
        )


def reverse_payment_statuses(apps, schema_editor):
    """Reverse: 'no_charge' → 'n/a'"""
    Service = apps.get_model("services", "Service")
    Service.objects.filter(payment_status="no_charge").update(
        payment_status="n/a"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0056_rename_na_to_no_charge'),
    ]

    operations = [
        migrations.RunPython(
            migrate_payment_statuses,
            reverse_payment_statuses,
        ),
    ]
