# Generated by Django 5.2.3 on 2026-04-03 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0057_migrate_payment_status_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyasset',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Price the asset was sold for (sub-stall revenue)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='companyasset',
            name='sold_to',
            field=models.CharField(blank=True, help_text='Name of buyer when asset is sold', max_length=255),
        ),
    ]
