# Generated by Django 5.2.3 on 2026-04-03 03:57

import django.db.models.deletion
from django.db import migrations, models


def clear_empty_sold_to(apps, schema_editor):
    """Drop NOT NULL, then set empty strings to NULL so the column can be cast to bigint."""
    schema_editor.execute(
        "ALTER TABLE services_companyasset ALTER COLUMN sold_to DROP NOT NULL"
    )
    schema_editor.execute(
        "UPDATE services_companyasset SET sold_to = NULL WHERE sold_to = ''"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0011_drop_legacy_is_favorite_column'),
        ('services', '0058_add_sale_fields_to_company_asset'),
    ]

    operations = [
        migrations.RunPython(clear_empty_sold_to, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='companyasset',
            name='sold_to',
            field=models.ForeignKey(blank=True, help_text='Client who purchased this asset', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchased_assets', to='clients.client'),
        ),
    ]
