# Generated by Django 5.2.3 on 2026-04-14 15:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_default_service_part_templates(apps, schema_editor):
    ServicePartTemplate = apps.get_model('services', 'ServicePartTemplate')
    ServicePartTemplateLine = apps.get_model('services', 'ServicePartTemplateLine')

    template, created = ServicePartTemplate.objects.get_or_create(
        name='Installation',
        defaults={
            'description': 'Standard line set and consumables for installation jobs.',
        },
    )

    if not created and template.lines.exists():
        return

    lines = [
        ('1/4 Copper Pipe', Decimal('10.00')),
        ('3/8 Copper Pipe', Decimal('10.00')),
        ('1/4 Insulation Tube', Decimal('1.00')),
        ('3/8 Insulation Tube', Decimal('1.00')),
        ('Polythene Tape', Decimal('1.00')),
    ]

    ServicePartTemplateLine.objects.bulk_create([
        ServicePartTemplateLine(
            template=template,
            item_name=item_name,
            quantity=quantity,
            sort_order=index,
        )
        for index, (item_name, quantity) in enumerate(lines)
    ])


def reverse_seed_default_service_part_templates(apps, schema_editor):
    ServicePartTemplate = apps.get_model('services', 'ServicePartTemplate')
    ServicePartTemplate.objects.filter(name='Installation').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0060_add_serviceextracharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePartTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_part_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Service Part Template',
                'verbose_name_plural': 'Service Part Templates',
                'ordering': ['name', '-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ServicePartTemplateLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='services.serviceparttemplate')),
            ],
            options={
                'verbose_name': 'Service Part Template Line',
                'verbose_name_plural': 'Service Part Template Lines',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.RunPython(
            seed_default_service_part_templates,
            reverse_seed_default_service_part_templates,
        ),
    ]
