# Generated by Django 5.2.3 on 2026-04-14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def migrate_template_lines_and_cleanup_defaults(apps, schema_editor):
    ServicePartTemplate = apps.get_model("services", "ServicePartTemplate")
    ServicePartTemplateLine = apps.get_model("services", "ServicePartTemplateLine")
    Item = apps.get_model("inventory", "Item")

    # Remove seeded default template so users start with a clean slate.
    ServicePartTemplate.objects.filter(
        name="Installation",
        description="Standard line set and consumables for installation jobs.",
        created_by__isnull=True,
    ).delete()

    # Migrate legacy item_name values to either inventory item link or custom description.
    for line in ServicePartTemplateLine.objects.all().iterator():
        legacy_name = (getattr(line, "item_name", "") or "").strip()
        if not legacy_name:
            continue

        matched_item = Item.objects.filter(name__iexact=legacy_name).first()
        if matched_item:
            line.item_id = matched_item.id
            line.custom_description = ""
        else:
            line.item_id = None
            line.custom_description = legacy_name

        line.save(update_fields=["item", "custom_description"])


def reverse_migration(apps, schema_editor):
    # No-op reverse: this migration intentionally normalizes to the new schema.
    return


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0049_direct_stock_request"),
        ("services", "0061_alter_serviceextracharge_id_serviceparttemplate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceparttemplateline",
            name="item",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="service_part_template_lines",
                to="inventory.item",
            ),
        ),
        migrations.AddField(
            model_name="serviceparttemplateline",
            name="custom_description",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="serviceparttemplateline",
            name="custom_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.RunPython(
            migrate_template_lines_and_cleanup_defaults,
            reverse_migration,
        ),
        migrations.RemoveField(
            model_name="serviceparttemplateline",
            name="item_name",
        ),
    ]
