# Generated by Django 5.2.3 on 2026-07-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0062_service_part_template_lines_inventory_or_custom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceextracharge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='servicepayment',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('credit', 'Credit'), ('debit', 'Debit'), ('cheque', 'Cheque'), ('fund', 'Client Fund')], max_length=10),
        ),
    ]
