# Generated by Django 5.2.3 on 2025-06-29 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='phone',
            new_name='contact_number',
        ),
    ]
