# Generated by Django 5.2.3 on 2025-08-11 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_add_partial_unique_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='is_blocklisted',
            field=models.BooleanField(default=False),
        ),
    ]
