# Generated by Django 5.2.3 on 2026-03-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_deleted_at'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['full_name'], name='clients_cli_full_na_193c54_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted'], name='clients_cli_is_dele_4bb44e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_deleted', '-created_at'], name='clients_cli_is_dele_45b378_idx'),
        ),
    ]
