# Generated by Django 5.2.3 on 2026-07-13 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0012_client_fund_balance_and_deposits'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='clientfunddeposit',
            new_name='clients_cli_client__2e35e7_idx',
            old_name='clients_cli_client__7c2f7c_idx',
        ),
        migrations.RenameIndex(
            model_name='clientfunddeposit',
            new_name='clients_cli_deposit_054530_idx',
            old_name='clients_cli_deposit__b2f0c5_idx',
        ),
    ]
