# Generated by Django 5.2.3 on 2025-07-22 04:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0029_item_cost_price_item_technician_price_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RemittanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('total_sales_cash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales_gcash', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales_credit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales_debit', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_sales_cheque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remitted_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remitted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('remitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stall')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stall', 'date')},
            },
        ),
        migrations.CreateModel(
            name='CashDenominationBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_1000', models.PositiveIntegerField(default=0)),
                ('count_500', models.PositiveIntegerField(default=0)),
                ('count_100', models.PositiveIntegerField(default=0)),
                ('count_50', models.PositiveIntegerField(default=0)),
                ('count_20', models.PositiveIntegerField(default=0)),
                ('count_10', models.PositiveIntegerField(default=0)),
                ('count_5', models.PositiveIntegerField(default=0)),
                ('count_1', models.PositiveIntegerField(default=0)),
                ('remittance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cash_breakdown', to='remittances.remittancerecord')),
            ],
            options={
                'verbose_name': 'Cash Denomination Breakdown',
                'verbose_name_plural': 'Cash Denomination Breakdowns',
            },
        ),
    ]
