# Generated by Django 5.2.3 on 2025-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remittancerecord',
            old_name='remitted_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='coins_remitted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='coins_remitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='is_remitted',
            field=models.BooleanField(default=False),
        ),
    ]
