# Generated by Django 5.2.3 on 2025-07-26 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_item_cost_price_item_technician_price_and_more'),
        ('remittances', '0002_rename_remitted_at_remittancerecord_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='remittancerecord',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='remittancerecord',
            unique_together={('stall', 'created_at')},
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.RemoveField(
            model_name='remittancerecord',
            name='date',
        ),
    ]
