# Generated by Django 5.2.3 on 2025-07-27 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0003_alter_remittancerecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashdenominationbreakdown',
            name='coins_remitted',
        ),
        migrations.RemoveField(
            model_name='remittancerecord',
            name='coins_remitted',
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='count_200',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_1',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_10',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_100',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_1000',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_20',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_200',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_5',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_50',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashdenominationbreakdown',
            name='declared_count_500',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='declared_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
