# Generated by Django 5.2.3 on 2026-03-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0004_remove_cashdenominationbreakdown_coins_remitted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancerecord',
            name='manually_adjusted',
            field=models.BooleanField(default=False),
        ),
    ]
