# Generated by Django 5.2.3 on 2026-03-13 13:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0044_stockrequest'),
        ('remittances', '0006_add_remittance_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='remittancerecord',
            index=models.Index(fields=['remittance_date'], name='remittances_remitta_2131c7_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancerecord',
            index=models.Index(fields=['is_remitted'], name='remittances_is_remi_631fa0_idx'),
        ),
        migrations.AddIndex(
            model_name='remittancerecord',
            index=models.Index(fields=['stall', '-created_at'], name='remittances_stall_i_a63ade_idx'),
        ),
    ]
