# Generated by Django 5.2.3 on 2026-07-07 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remittances', '0008_add_client_fund_deposits'),
    ]

    operations = [
        migrations.AddField(
            model_name='remittancerecord',
            name='client_fund_deposits_cash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='client_fund_deposits_cash_override',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='client_fund_deposits_cheque',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='client_fund_deposits_credit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='client_fund_deposits_debit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='remittancerecord',
            name='client_fund_deposits_gcash',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
