# Generated by Django 5.2.3 on 2025-06-25 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_productcategory_alter_item_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='price',
            new_name='srp',
        ),
    ]
