# Generated by Django 5.2.3 on 2025-06-25 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockroomstock_stocktransfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockroomstock',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AddConstraint(
            model_name='stockroomstock',
            constraint=models.UniqueConstraint(fields=('item',), name='unique_item_stockroom'),
        ),
    ]
