# Generated by Django 5.2.3 on 2025-06-25 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_stockroomstock_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stockroomstock',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockroomstock',
            name='item',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
    ]
