# Generated by Django 5.2.3 on 2025-06-27 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_stocktransfer_technician'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockroomstock',
            options={'ordering': ['item__name']},
        ),
    ]
