# Generated by Django 5.2.3 on 2025-07-03 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_productcategory_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='is_deleted',
        ),
    ]
