# Generated by Django 5.2.3 on 2025-07-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_productcategory_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.CharField(choices=[('bought', 'Bought Outside'), ('transferred', 'From Stock Room')], default='bought', max_length=20),
        ),
    ]
