# Generated by Django 5.2.3 on 2025-07-04 05:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stock_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('source', models.CharField(choices=[('stock_room', 'Stock Room'), ('bought', 'Bought Outside'), ('transfer', 'Transfer From Another Stall')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('related_transfer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='inventory.stocktransfer')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.stall')),
            ],
        ),
    ]
