# Generated by Django 5.2.3 on 2025-07-04 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_stockmovement'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stock',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='stock',
            name='type',
        ),
    ]
