# Generated by Django 5.2.3 on 2025-07-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_alter_stock_unique_together_remove_stock_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
