# Generated by Django 5.2.3 on 2025-07-07 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stock_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stocktransfer',
            options={'ordering': ['-transfer_date']},
        ),
        migrations.RemoveField(
            model_name='item',
            name='size_or_spec',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_expense',
            field=models.BooleanField(default=False),
        ),
    ]
