# Generated by Django 5.2.3 on 2025-07-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0017_alter_stocktransfer_options_remove_item_size_or_spec_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='srp',
            new_name='retail_price',
        ),
    ]
