# Generated by Django 5.2.3 on 2025-07-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0018_rename_srp_item_retail_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockroomstock',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
