# Generated by Django 5.2.3 on 2025-07-07 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0019_stockroomstock_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='stall',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.stall'),
        ),
    ]
