# Generated by Django 5.2.3 on 2025-07-07 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0020_alter_stockmovement_stall'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('stock_room', 'Stock Room'), ('bought', 'Bought Outside'), ('transfer', 'Transfer From Another Stall')], max_length=100),
        ),
    ]
