# Generated by Django 5.2.3 on 2025-07-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0021_alter_stockmovement_source'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stocktransfer',
            name='is_expense',
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stocktransfer',
            name='is_finalized',
            field=models.BooleanField(default=False),
        ),
    ]
