# Generated by Django 5.2.3 on 2025-07-09 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0022_remove_stocktransfer_is_expense_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransfer',
            name='used_for',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
