# Generated by Django 5.2.3 on 2025-07-13 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stocktransfer_used_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('stock_room', 'Stock Room'), ('bought', 'Bought Outside'), ('transfer', 'Transfer From Another Stall'), ('related_sales', 'Related Sales')], max_length=100),
        ),
    ]
