# Generated by Django 5.2.3 on 2025-07-13 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0024_alter_stockmovement_source'),
        ('sales', '0006_salestransaction_sales_clerk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='source',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment'), ('return', 'Return')], default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='note',
            field=models.CharField(blank=True, help_text='Optional description / reason', max_length=255),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='related_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='sales.salestransaction'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.IntegerField(help_text='Positive for stock in, negative for stock out'),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='related_transfer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='inventory.stocktransfer'),
        ),
    ]
