# Generated by Django 5.2.3 on 2025-07-14 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('inventory', '0026_alter_stock_item_alter_stock_stall_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['item__name']},
        ),
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_restock',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_sale',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='related_transfer',
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
