# Generated by Django 5.2.3 on 2025-07-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0027_alter_stock_options_alter_stockmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment'), ('return', 'Return'), ('restore_sale', 'Restore Sale'), ('void_sale', 'Void Sale')], max_length=50),
        ),
    ]
