# Generated by Django 5.2.3 on 2025-08-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0029_item_cost_price_item_technician_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='track_stock',
            field=models.BooleanField(default=True),
        ),
    ]
