# Generated by Django 5.2.3 on 2025-10-12 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0030_stock_track_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
