# Generated by Django 5.2.3 on 2025-10-17 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0031_stock_reserved_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stockmovement',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='item',
        ),
        migrations.RemoveField(
            model_name='stockmovement',
            name='stall',
        ),
        migrations.DeleteModel(
            name='Restock',
        ),
        migrations.DeleteModel(
            name='StockMovement',
        ),
    ]
