# Generated by Django 5.2.3 on 2025-12-03 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_single_stockroom_enforcement'),
        ('inventory', '0032_remove_stockmovement_content_type_and_more'),
    ]

    operations = [
    ]
