# Generated by Django 5.2.3 on 2025-12-04 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0033_merge_20251203_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='stall',
            name='inventory_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stall',
            name='is_system',
            field=models.BooleanField(default=False),
        ),
    ]
