# Generated by Django 5.2.3 on 2026-03-12 04:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0042_decimal_quantities_and_waste_tolerance'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retail_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('wholesale_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('technician_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('old_retail_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_wholesale_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_technician_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('old_cost_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('change_type', models.CharField(choices=[('initial', 'Initial Price'), ('price', 'Price Change')], default='price', max_length=20)),
                ('notes', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='inventory.item')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
