# Generated by Django 5.2.3 on 2026-03-12 04:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0043_itempricehistory'),
        ('services', '0033_applianceitemused_stock_request_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_quantity', models.DecimalField(decimal_places=2, help_text='Amount of stock to add (the deficit between needed and available).', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('source', models.CharField(choices=[('service_appliance', 'Service Appliance Item'), ('service', 'Service Item')], help_text='Whether this request originated from an appliance item or service-level item.', max_length=20)),
                ('notes', models.TextField(blank=True, default='', help_text='Clerk notes explaining why stock is needed.')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('decline_reason', models.TextField(blank=True, default='')),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('appliance_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='services.applianceitemused')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_approved', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='inventory.item')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests_made', to=settings.AUTH_USER_MODEL)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='services.service')),
                ('service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='services.serviceitemused')),
                ('stall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_requests', to='inventory.stall')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
