# Generated by Django 5.2.3 on 2026-03-16 12:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0045_add_price_validators'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomItemTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Template item name', max_length=255)),
                ('default_price', models.DecimalField(decimal_places=2, help_text='Default price per unit', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('description', models.TextField(blank=True, default='', help_text='Optional notes or description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_item_templates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Item Template',
                'verbose_name_plural': 'Custom Item Templates',
                'ordering': ['name'],
            },
        ),
    ]
