# Generated by Django 5.2.3 on 2026-07-13 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0049_direct_stock_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directstockrequestbatch',
            name='notes',
            field=models.TextField(blank=True, default='', help_text='Clerk notes for the overall batch request.'),
        ),
    ]
