# Generated by Django 5.2.3 on 2026-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_add_access_jti_to_authsession'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='authsession',
            name='authenticati_access__jti_idx',
        ),
        migrations.RenameIndex(
            model_name='authsession',
            new_name='authenticat_user_id_9bc38a_idx',
            old_name='authenticati_user_id_2d2d40_idx',
        ),
        migrations.RenameIndex(
            model_name='authsession',
            new_name='authenticat_device__55caa7_idx',
            old_name='authenticati_device__2f87de_idx',
        ),
        migrations.AlterField(
            model_name='authsession',
            name='access_jti',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
