# Generated by Django 5.2.3 on 2026-01-05 02:47

import datetime
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PayrollSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_start', models.TimeField(default=datetime.time(8, 0))),
                ('shift_end', models.TimeField(default=datetime.time(18, 0))),
                ('grace_minutes', models.PositiveIntegerField(default=15, help_text='Threshold-only grace minutes for attendance classification.')),
                ('auto_close_enabled', models.BooleanField(default=True, help_text='Auto-close sessions missing clock_out at shift_end and mark as auto_closed.')),
                ('holiday_special_pct', models.DecimalField(decimal_places=2, default=Decimal('0.30'), help_text='Premium rate for special non-working holidays applied to base daily-rate portion.', max_digits=5)),
                ('holiday_regular_pct', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Premium rate for regular holidays applied to base daily-rate portion.', max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payroll Settings',
                'verbose_name_plural': 'Payroll Settings',
            },
        ),
        migrations.CreateModel(
            name='AdditionalEarning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earning_date', models.DateField()),
                ('category', models.CharField(choices=[('overtime', 'Overtime'), ('installation_pct', 'Installation Percentage'), ('custom', 'Custom')], default='custom', max_length=32)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('approved', models.BooleanField(default=True, help_text='Only approved additional earnings are included in payroll computations.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-earning_date'],
                'indexes': [models.Index(fields=['employee', 'earning_date'], name='payroll_add_employe_eff867_idx'), models.Index(fields=['earning_date'], name='payroll_add_earning_b7884a_idx'), models.Index(fields=['approved'], name='payroll_add_approve_95092e_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clock_in', models.DateTimeField()),
                ('clock_out', models.DateTimeField()),
                ('unpaid_break_minutes', models.PositiveIntegerField(default=0)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('schedule', 'From Schedule'), ('import', 'Imported')], default='manual', max_length=20)),
                ('approved', models.BooleanField(default=True, help_text='Only approved entries are included in payroll computations.')),
                ('notes', models.TextField(blank=True)),
                ('auto_closed', models.BooleanField(default=False, help_text='True if the session was auto-closed at shift end due to missing clock_out.')),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-clock_in'],
                'indexes': [models.Index(fields=['employee', 'clock_in'], name='payroll_tim_employe_9945cc_idx'), models.Index(fields=['clock_in'], name='payroll_tim_clock_i_d4adae_idx'), models.Index(fields=['approved'], name='payroll_tim_approve_312a3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeeklyPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateField(help_text='Start date of the payroll week (recommended: Monday).')),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('overtime_threshold', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=5)),
                ('overtime_multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.50'), max_digits=4)),
                ('regular_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6)),
                ('allowances', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('additional_earnings_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('gross_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('deductions', models.JSONField(default=dict, help_text='Map of deduction name -> amount. Example: {"Tax": 120.55, "Benefits": 35.00}')),
                ('total_deductions', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('net_pay', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekly_payrolls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-week_start', 'employee_id'],
                'indexes': [models.Index(fields=['employee', 'week_start'], name='payroll_wee_employe_426d51_idx'), models.Index(fields=['status'], name='payroll_wee_status_4dbdc9_idx')],
                'unique_together': {('employee', 'week_start')},
            },
        ),
    ]
