# Generated by Django 5.2.3 on 2026-01-06 09:39

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='night_diff_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Night differential additional multiplier applied to ND hours (e.g., 0.10 = +10%).', max_digits=4),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='overtime_multiplier',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.25'), help_text='Overtime pay multiplier applied to overtime hours (e.g., 1.25 = +25%).', max_digits=4),
        ),
        migrations.CreateModel(
            name='DeductionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('sss', 'SSS'), ('philhealth', 'PhilHealth'), ('pagibig', 'Pag-IBIG')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('effective_start', models.DateField(help_text='Date the rate becomes effective (inclusive).')),
                ('effective_end', models.DateField(blank=True, help_text='Date the rate stops being effective (inclusive). Leave null if still active.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deduction_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Deduction Rate',
                'verbose_name_plural': 'Deduction Rates',
                'ordering': ['name', '-effective_start'],
                'indexes': [models.Index(fields=['name', 'effective_start'], name='payroll_ded_name_dfd606_idx'), models.Index(fields=['name', 'is_active'], name='payroll_ded_name_173015_idx')],
            },
        ),
    ]
