# Generated by Django 5.2.3 on 2026-01-06 12:00

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_payrollsettings_night_diff_multiplier_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklypayroll",
            name="night_diff_hours",
            field=models.DecimalField(
                max_digits=6, decimal_places=2, default=Decimal("0.00")
            ),
        ),
        migrations.AddField(
            model_name="weeklypayroll",
            name="night_diff_pay",
            field=models.DecimalField(
                max_digits=12, decimal_places=2, default=Decimal("0.00")
            ),
        ),
        migrations.AddField(
            model_name="weeklypayroll",
            name="approved_ot_hours",
            field=models.DecimalField(
                max_digits=6, decimal_places=2, default=Decimal("0.00")
            ),
        ),
        migrations.AddField(
            model_name="weeklypayroll",
            name="approved_ot_pay",
            field=models.DecimalField(
                max_digits=12, decimal_places=2, default=Decimal("0.00")
            ),
        ),
    ]
