# Generated by Django 5.2.3 on 2026-01-06 12:30

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_weeklypayroll_add_nd_and_ot_fields"),
    ]

    operations = [
        # Create Holiday model
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("date", models.DateField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "kind",
                    models.CharField(
                        max_length=32,
                        choices=[
                            ("regular", "Regular Holiday"),
                            ("special_non_working", "Special Non-Working Holiday"),
                        ],
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-date"],
                "indexes": [
                    models.Index(fields=["date", "kind"], name="payroll_hol_date_kind_idx"),
                ],
            },
        ),
        # WeeklyPayroll holiday fields (computed)
        migrations.AddField(
            model_name="weeklypayroll",
            name="holiday_pay_regular",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=Decimal("0.00")),
        ),
        migrations.AddField(
            model_name="weeklypayroll",
            name="holiday_pay_special",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=Decimal("0.00")),
        ),
        migrations.AddField(
            model_name="weeklypayroll",
            name="holiday_pay_total",
            field=models.DecimalField(max_digits=12, decimal_places=2, default=Decimal("0.00")),
        ),
        # PayrollSettings additional holiday-related settings
        migrations.AddField(
            model_name="payrollsettings",
            name="holiday_day_hours",
            field=models.DecimalField(
                max_digits=5,
                decimal_places=2,
                default=Decimal("8.00"),
                help_text="Hours used to compute daily rate (hourly_rate * day_hours).",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="regular_holiday_no_work_pays",
            field=models.BooleanField(
                default=True,
                help_text="Pay +100% daily even if no work on regular holiday.",
            ),
        ),
        migrations.AddField(
            model_name="payrollsettings",
            name="special_holiday_no_work_pays",
            field=models.BooleanField(
                default=False,
                help_text="Pay +30% daily even if no work on special non-working holiday.",
            ),
        ),
    ]
