# Generated by Django 5.2.3 on 2026-01-06 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_holidays_and_holiday_pay_fields'),
        ('payroll', '0004_overtimerequest'),
    ]

    operations = [
    ]
