# Generated by Django 5.2.3 on 2026-01-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0005_merge_20260106_2218'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='holiday',
            new_name='payroll_hol_date_cde140_idx',
            old_name='payroll_hol_date_kind_idx',
        ),
    ]
