# Generated by Django 5.2.3 on 2026-01-29 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0006_rename_payroll_hol_date_kind_idx_payroll_hol_date_cde140_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='payroll_cutoff_day',
            field=models.PositiveIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=4, help_text='Last day of payroll week (0=Monday, 4=Friday). Week starts the day after this cutoff.'),
        ),
    ]
