# Generated by Django 5.2.3 on 2026-01-29 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_payrollsettings_payroll_cutoff_day'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeEntry',
        ),
    ]
