# Generated by Django 5.2.3 on 2026-01-29 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0008_remove_timeentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OvertimeRequest',
        ),
    ]
