# Generated by Django 5.2.3 on 2026-01-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0009_delete_overtimerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayroll',
            name='disputed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='weeklypayroll',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklypayroll',
            name='disputed_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='weeklypayroll',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='weeklypayroll',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payrolls', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklypayroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid'), ('received', 'Received')], default='draft', max_length=20),
        ),
    ]
