# Generated by Django 5.2.3 on 2026-01-30 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0010_weeklypayroll_disputed_weeklypayroll_disputed_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Deduction name (e.g., Loan, Uniform, Cash Advance)', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('deduction_type', models.CharField(choices=[('per_employee', 'Per Employee'), ('recurring_all', 'Recurring for All'), ('onetime_all', 'One-Time for All')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField(help_text='Date when deduction becomes effective')),
                ('end_date', models.DateField(blank=True, help_text='Optional end date for recurring deductions', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('applied_date', models.DateField(blank=True, help_text='Date when onetime deduction was applied', null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_deductions', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(blank=True, help_text='Required for per_employee deductions', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='manual_deductions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['deduction_type', 'is_active'], name='payroll_man_deducti_e835f1_idx'), models.Index(fields=['employee', 'is_active'], name='payroll_man_employe_4ee537_idx'), models.Index(fields=['effective_date'], name='payroll_man_effecti_c9af8a_idx')],
            },
        ),
    ]
