# Generated by Django 5.2.3 on 2026-01-30 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0012_add_tax_bracket_and_percentage_deduction'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='percentagededuction',
            new_name='payroll_per_deducti_a696d0_idx',
            old_name='payroll_per_deducti_idx',
        ),
        migrations.RenameIndex(
            model_name='percentagededuction',
            new_name='payroll_per_effecti_30d20c_idx',
            old_name='payroll_per_effecti_idx',
        ),
        migrations.RenameIndex(
            model_name='taxbracket',
            new_name='payroll_tax_effecti_cd234a_idx',
            old_name='payroll_tax_effecti_idx',
        ),
        migrations.AlterField(
            model_name='manualdeduction',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date when deduction becomes effective. Required for recurring deductions, optional for one-time (auto-applied to next payroll)', null=True),
        ),
    ]
