# Generated by Django 5.2.3 on 2026-01-30 09:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0013_make_effective_date_nullable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GovernmentBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('sss', 'SSS'), ('philhealth', 'PhilHealth'), ('pagibig', 'Pag-IBIG / HDMF'), ('bir_tax', 'BIR Withholding Tax')], max_length=20)),
                ('name', models.CharField(help_text="Display name (e.g., 'SSS Contribution')", max_length=100)),
                ('calculation_method', models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Gross'), ('progressive_tax', 'Progressive Tax Bracket')], max_length=20)),
                ('employee_share_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed employee contribution amount (weekly)', max_digits=12, null=True)),
                ('employer_share_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed employer contribution amount (weekly)', max_digits=12, null=True)),
                ('employee_share_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Employee percentage rate (e.g., 0.045 for 4.5%)', max_digits=5, null=True)),
                ('employer_share_rate', models.DecimalField(blank=True, decimal_places=4, help_text='Employer percentage rate (e.g., 0.08 for 8%)', max_digits=5, null=True)),
                ('effective_start', models.DateField(help_text='Date this benefit configuration becomes effective')),
                ('effective_end', models.DateField(blank=True, help_text='Date this benefit configuration ends (null = still active)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_government_benefits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_start', 'benefit_type'],
                'indexes': [models.Index(fields=['benefit_type', 'is_active'], name='payroll_gov_benefit_8017f5_idx'), models.Index(fields=['effective_start', 'effective_end'], name='payroll_gov_effecti_e1a028_idx')],
            },
        ),
        migrations.CreateModel(
            name='PayrollDeduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('manual', 'Manual Deduction'), ('government', 'Government Benefit'), ('tax', 'Withholding Tax'), ('late_penalty', 'Late Penalty'), ('other', 'Other')], max_length=20)),
                ('name', models.CharField(help_text="Deduction name (e.g., 'SSS', 'Loan Repayment')", max_length=100)),
                ('description', models.TextField(blank=True)),
                ('employee_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text="Amount deducted from employee's pay", max_digits=12)),
                ('employer_share', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount paid by employer (for reporting, not deducted from employee)', max_digits=12)),
                ('source_type', models.CharField(blank=True, help_text="Source model name (e.g., 'ManualDeduction', 'GovernmentBenefit')", max_length=50)),
                ('source_id', models.IntegerField(blank=True, help_text='ID of the source record', null=True)),
                ('calculation_method', models.CharField(blank=True, help_text='How this was calculated (fixed, percentage, progressive_tax)', max_length=20)),
                ('basis_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Base amount used for calculation (e.g., gross pay for percentage deductions)', max_digits=12, null=True)),
                ('rate', models.DecimalField(blank=True, decimal_places=4, help_text='Rate used for percentage calculations', max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payroll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deduction_items', to='payroll.weeklypayroll')),
            ],
            options={
                'ordering': ['category', 'name'],
                'indexes': [models.Index(fields=['payroll', 'category'], name='payroll_pay_payroll_ab1802_idx'), models.Index(fields=['source_type', 'source_id'], name='payroll_pay_source__ee620a_idx')],
            },
        ),
    ]
