# Generated by Django 5.2.3 on 2026-01-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0014_add_government_benefit_and_payroll_deduction'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklypayroll',
            name='deduction_metadata',
            field=models.JSONField(default=dict, help_text='Metadata for deductions including source info. Example: {"loan": {"source_type": "ManualDeduction", "source_id": 123, "category": "manual"}}'),
        ),
    ]
