# Generated by Django 5.2.3 on 2026-01-31 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0015_weeklypayroll_deduction_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklypayroll',
            name='overtime_hours',
        ),
        migrations.DeleteModel(
            name='PayrollDeduction',
        ),
    ]
