# Generated by Django 5.2.3 on 2026-01-31 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0016_remove_weeklypayroll_overtime_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentbenefit',
            name='period_type',
            field=models.CharField(choices=[('weekly', 'Weekly (amount as-is)'), ('monthly', 'Monthly (divide by 4 for weekly payroll)')], default='monthly', help_text='Whether the fixed amount is monthly (divide by 4) or weekly (as-is)', max_length=10),
        ),
        migrations.AlterField(
            model_name='governmentbenefit',
            name='employee_share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed employee contribution amount (monthly or weekly based on period_type)', max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='governmentbenefit',
            name='employer_share_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Fixed employer contribution amount (monthly or weekly based on period_type)', max_digits=12, null=True),
        ),
    ]
