# Generated by Django 5.2.3 on 2026-01-31 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0017_governmentbenefit_period_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalearning',
            name='category',
            field=models.CharField(
                choices=[
                    ('installation_pct', 'Installation Percentage'),
                    ('custom', 'Custom'),
                ],
                default='custom',
                max_length=32
            ),
        ),
    ]
