# Generated by Django 5.2.3 on 2026-01-31 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0018_remove_overtime_from_additional_earnings'),
    ]

    operations = [
        migrations.AddField(
            model_name='taxbracket',
            name='bracket_type',
            field=models.CharField(
                choices=[
                    ('bir', 'BIR Withholding Tax'),
                    ('sss', 'SSS Contribution'),
                    ('philhealth', 'PhilHealth Contribution'),
                    ('pagibig', 'Pag-IBIG Contribution'),
                    ('custom', 'Custom Tax/Contribution'),
                ],
                default='bir',
                help_text='Type of tax bracket (BIR, SSS, PhilHealth, Pag-IBIG, etc.)',
                max_length=32,
            ),
        ),
        migrations.AlterModelOptions(
            name='taxbracket',
            options={'ordering': ['bracket_type', 'min_income']},
        ),
        migrations.AddIndex(
            model_name='taxbracket',
            index=models.Index(fields=['bracket_type', 'effective_start', 'is_active'], name='payroll_tax_bracket_type_idx'),
        ),
    ]
