# Generated by Django 5.2.3 on 2026-02-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0019_taxbracket_bracket_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='taxbracket',
            new_name='payroll_tax_bracket_527279_idx',
            old_name='payroll_tax_bracket_type_idx',
        ),
    ]
