# Generated by Django 5.2.3 on 2026-02-05 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0020_rename_payroll_tax_bracket_type_idx_payroll_tax_bracket_527279_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeBenefitOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_type', models.CharField(choices=[('sss', 'SSS'), ('philhealth', 'PhilHealth'), ('pagibig', 'Pag-IBIG / HDMF'), ('bir_tax', 'BIR Withholding Tax')], max_length=20)),
                ('employee_share_amount', models.DecimalField(decimal_places=2, help_text='Fixed employee contribution amount per week', max_digits=12)),
                ('employer_share_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Fixed employer contribution amount per week (for reporting)', max_digits=12, null=True)),
                ('effective_start', models.DateField(help_text='Date this override becomes effective')),
                ('effective_end', models.DateField(blank=True, help_text='Date this override ends (null = still active)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for override or special notes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_benefit_overrides', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefit_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-effective_start', 'employee', 'benefit_type'],
                'indexes': [models.Index(fields=['employee', 'benefit_type', 'is_active'], name='payroll_emp_employe_041e64_idx'), models.Index(fields=['effective_start', 'effective_end'], name='payroll_emp_effecti_52ee02_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'benefit_type', 'effective_start'), name='unique_employee_benefit_start_date')],
            },
        ),
    ]
