# Generated by Django 5.2.3 on 2026-02-07 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0021_employeebenefitoverride'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='clock_out_tolerance_minutes',
            field=models.PositiveIntegerField(default=30, help_text='Grace minutes BEFORE shift_end that still counts as full day (e.g., 30 = clocking out at 5:30 PM still counts as full day when shift ends at 6:00 PM).'),
        ),
    ]
