# Generated by Django 5.2.3 on 2026-02-07 11:28

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0022_payrollsettings_clock_out_tolerance_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='cash_ban_contribution_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.05'), help_text="Percentage of gross pay to contribute to employee's cash ban fund (e.g., 0.05 = 5%).", max_digits=5),
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='cash_ban_enabled',
            field=models.BooleanField(default=True, help_text='Enable automatic cash ban contributions when approving payroll.'),
        ),
    ]
