# Generated by Django 5.2.3 on 2026-02-07 11:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_payrollsettings_cash_ban_contribution_rate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payrollsettings',
            name='cash_ban_contribution_rate',
        ),
        migrations.AddField(
            model_name='payrollsettings',
            name='cash_ban_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('100.00'), help_text="Fixed amount to contribute to employee's cash ban fund per payroll period.", max_digits=10),
        ),
    ]
