# Generated by Django 5.1 on 2026-02-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0023_payrollsettings_cash_ban_contribution_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='clock_in_allowance_minutes',
            field=models.PositiveIntegerField(
                default=60,
                help_text='Minutes BEFORE shift_start employees can clock in (e.g., 60 = can clock in at 7:00 AM for 8:00 AM shift). Paid hours count from shift_start, not early clock-in.',
            ),
        ),
    ]
