# Generated by manual creation

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_payrollsettings_clock_in_allowance_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='payrollsettings',
            name='attendance_system_start_date',
            field=models.DateField(blank=True, help_text='Date when attendance system started. Absences will not be marked before this date.', null=True),
        ),
    ]
