# Generated by Django 5.2.3 on 2026-02-13 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0024_remove_payrollsettings_cash_ban_contribution_rate_and_more'),
        ('payroll', '0025_payrollsettings_attendance_system_start_date'),
    ]

    operations = [
    ]
