# Generated by Django 5.2.3 on 2026-02-13 14:13

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_merge_20260213_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalearning',
            name='category',
            field=models.CharField(choices=[('bonus', 'Bonus'), ('commission', 'Commission'), ('tip', 'Customer Tip'), ('performance', 'Performance Incentive'), ('installation_pct', 'Installation %'), ('allowance', 'Special Allowance'), ('other', 'Other')], default='other', max_length=32),
        ),
        migrations.AlterField(
            model_name='payrollsettings',
            name='cash_ban_contribution_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('200.00'), help_text="Fixed amount to contribute to employee's cash ban fund per payroll period.", max_digits=10),
        ),
    ]
