# Generated by Django 5.2.3 on 2026-02-16 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_merge_20260213_1002'),
        ('payroll', '0027_alter_additionalearning_category_and_more'),
    ]

    operations = [
    ]
