# Generated by Django 5.1.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0026_merge_20260210_1730'),
        ('payroll', '0028_merge_20260216_1242'),
        ('payroll', '0028_weeklypayroll_week_end'),
    ]

    operations = [
    ]
