# Generated by Django 5.2.3 on 2026-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0030_add_deleted_at_soft_delete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklypayroll',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
    ]
