# Generated by Django 5.2.3 on 2026-03-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0031_alter_weeklypayroll_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualdeduction',
            name='is_recurring',
            field=models.BooleanField(default=False, help_text='For per_employee deductions: whether this repeats every payroll'),
        ),
    ]
