# Generated by Django 5.2.3 on 2026-03-10

from django.db import migrations


def backfill_is_recurring(apps, schema_editor):
    """
    Backfill is_recurring for existing per_employee deductions.
    Previously, recurring was implied by having an end_date set.
    Now we also mark deductions with end_date as recurring explicitly.
    """
    ManualDeduction = apps.get_model('payroll', 'ManualDeduction')
    ManualDeduction.objects.filter(
        deduction_type='per_employee',
        end_date__isnull=False,
    ).update(is_recurring=True)


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0032_manualdeduction_is_recurring'),
    ]

    operations = [
        migrations.RunPython(backfill_is_recurring, migrations.RunPython.noop),
    ]
