# Generated by Django 5.2.3 on 2026-04-03 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0034_unique_earning_constraint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentbenefit',
            name='calculation_method',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percentage', 'Percentage of Gross')], max_length=20),
        ),
        migrations.DeleteModel(
            name='TaxBracket',
        ),
    ]
