# Generated by Django 5.2.3 on 2026-04-03 05:01

from django.db import migrations


def update_progressive_tax_to_fixed(apps, schema_editor):
    """Convert any GovernmentBenefit records using progressive_tax to fixed."""
    GovernmentBenefit = apps.get_model('payroll', 'GovernmentBenefit')
    GovernmentBenefit.objects.filter(calculation_method='progressive_tax').update(
        calculation_method='fixed',
        employee_share_amount=0,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0035_remove_tax_bracket_model'),
    ]

    operations = [
        migrations.RunPython(update_progressive_tax_to_fixed, migrations.RunPython.noop),
    ]
