# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CCTVCamera",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=100)),
                ("uid", models.CharField(help_text="XMEye device serial number / cloud UID", max_length=200)),
                ("username", models.CharField(default="admin", max_length=100)),
                ("password", models.CharField(blank=True, max_length=100)),
                ("channel", models.PositiveSmallIntegerField(default=0, help_text="Camera channel: 0 = main lens, 1 = sub lens")),
                ("location", models.CharField(blank=True, max_length=200)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CCTV Camera",
                "verbose_name_plural": "CCTV Cameras",
                "ordering": ["order", "name"],
            },
        ),
    ]
