# Generated by Django 5.2.3 on 2026-02-01 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_enhance_notification_system'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_05b4bc_idx',
            old_name='notif_user_created_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_user_id_427e4b_idx',
            old_name='notif_user_read_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_type_ea918f_idx',
            old_name='notif_type_idx',
        ),
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_priorit_bf8ea0_idx',
            old_name='notif_priority_idx',
        ),
    ]
