# Generated by Django 5.2.3 on 2026-03-03 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_rename_notif_user_created_idx_notificatio_user_id_05b4bc_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notification',
            name='notificatio_priorit_bf8ea0_idx',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_text',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='action_url',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='expires_at',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='priority',
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_reminder', 'Payment Reminder'), ('payment_overdue', 'Payment Overdue'), ('service_created', 'New Service Created'), ('service_updated', 'Service Updated'), ('service_completed', 'Service Completed'), ('service_cancelled', 'Service Cancelled'), ('service_assigned', 'Service Assigned to You'), ('stock_low', 'Low Stock Alert'), ('stock_out', 'Out of Stock Alert'), ('stock_reorder', 'Reorder Point Reached'), ('stock_restocked', 'Stock Restocked'), ('warranty_claim_created', 'New Warranty Claim'), ('warranty_claim_approved', 'Warranty Claim Approved'), ('warranty_claim_rejected', 'Warranty Claim Rejected'), ('warranty_expiring', 'Warranty Expiring Soon'), ('free_cleaning_available', 'Free Cleaning Available'), ('sale_created', 'New Sale Created'), ('sale_voided', 'Sale Voided'), ('system_alert', 'System Alert'), ('report_ready', 'Report Ready')], help_text='Type of notification', max_length=50),
        ),
    ]
