# Generated by Django 5.2.3 on 2026-03-12 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_simplify_notification_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_reminder', 'Payment Reminder'), ('payment_overdue', 'Payment Overdue'), ('service_created', 'New Service Created'), ('service_updated', 'Service Updated'), ('service_completed', 'Service Completed'), ('service_cancelled', 'Service Cancelled'), ('service_assigned', 'Service Assigned to You'), ('stock_low', 'Low Stock Alert'), ('stock_out', 'Out of Stock Alert'), ('stock_reorder', 'Reorder Point Reached'), ('stock_restocked', 'Stock Restocked'), ('stock_request_created', 'Stock Request Created'), ('stock_request_approved', 'Stock Request Approved'), ('stock_request_declined', 'Stock Request Declined'), ('warranty_claim_created', 'New Warranty Claim'), ('warranty_claim_approved', 'Warranty Claim Approved'), ('warranty_claim_rejected', 'Warranty Claim Rejected'), ('warranty_expiring', 'Warranty Expiring Soon'), ('free_cleaning_available', 'Free Cleaning Available'), ('sale_created', 'New Sale Created'), ('sale_voided', 'Sale Voided'), ('system_alert', 'System Alert'), ('report_ready', 'Report Ready')], help_text='Type of notification', max_length=50),
        ),
    ]
