# Generated by Django 5.2.3 on 2026-03-16 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_add_items_review_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('payment_received', 'Payment Received'), ('payment_reminder', 'Payment Reminder'), ('payment_overdue', 'Payment Overdue'), ('service_created', 'New Service Created'), ('service_updated', 'Service Updated'), ('service_completed', 'Service Completed'), ('service_cancelled', 'Service Cancelled'), ('service_assigned', 'Service Assigned to You'), ('items_pending_review', 'Items Pending Review'), ('stock_low', 'Low Stock Alert'), ('stock_out', 'Out of Stock Alert'), ('stock_reorder', 'Reorder Point Reached'), ('stock_restocked', 'Stock Restocked'), ('stock_request_created', 'Stock Request Created'), ('stock_request_approved', 'Stock Request Approved'), ('stock_request_declined', 'Stock Request Declined'), ('stock_added_by_admin', 'Stock Added by Admin'), ('warranty_claim_created', 'New Warranty Claim'), ('warranty_claim_approved', 'Warranty Claim Approved'), ('warranty_claim_rejected', 'Warranty Claim Rejected'), ('warranty_expiring', 'Warranty Expiring Soon'), ('free_cleaning_available', 'Free Cleaning Available'), ('sale_created', 'New Sale Created'), ('sale_voided', 'Sale Voided'), ('attendance_approved', 'Attendance Approved'), ('attendance_rejected', 'Attendance Rejected'), ('leave_request_approved', 'Leave Request Approved'), ('leave_request_rejected', 'Leave Request Rejected'), ('overtime_approved', 'Overtime Request Approved'), ('overtime_rejected', 'Overtime Request Rejected'), ('work_request_approved', 'Work Request Approved'), ('work_request_declined', 'Work Request Declined'), ('payroll_available', 'Payroll Available'), ('system_alert', 'System Alert'), ('report_ready', 'Report Ready')], help_text='Type of notification', max_length=50),
        ),
    ]
