# Generated by Django 5.2.3 on 2026-04-01 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0008_add_push_subscription'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='pushsubscription',
            new_name='notificatio_user_id_d7f78b_idx',
            old_name='notifications_pushsub_user_idx',
        ),
    ]
