# Generated by Django 5.2.3 on 2025-08-19 05:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0005_client_is_blocklisted'),
        ('installations', '0001_initial'),
        ('inventory', '0030_stock_track_stock'),
        ('sales', '0008_salestransaction_change_amount'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconinstallation',
            name='service',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aircon_installation', to='services.service'),
        ),
        migrations.AddField(
            model_name='airconitemused',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.item'),
        ),
        migrations.AddField(
            model_name='airconmodel',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='installations.airconbrand'),
        ),
        migrations.AddField(
            model_name='airconunit',
            name='installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircon_unit', to='installations.airconinstallation'),
        ),
        migrations.AddField(
            model_name='airconunit',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='installations.airconmodel'),
        ),
        migrations.AddField(
            model_name='airconunit',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reserved_aircon_units', to='clients.client'),
        ),
        migrations.AddField(
            model_name='airconunit',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircon_units_sold', to='sales.salestransaction'),
        ),
        migrations.AddField(
            model_name='airconitemused',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_used', to='installations.airconunit'),
        ),
    ]
