# Generated by Django 5.2.3 on 2025-07-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('installations', '0001_initial'),
        ('sales', '0009_salesitem_aircon_unit'),
        ('services', '0003_airconinstallation_appliancetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconunit',
            name='installation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircon_unit', to='services.airconinstallation'),
        ),
        migrations.AddField(
            model_name='airconunit',
            name='sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircon_units_sold', to='sales.salestransaction'),
        ),
        migrations.AlterUniqueTogether(
            name='airconmodel',
            unique_together={('brand', 'model_name')},
        ),
    ]
