# Generated by Django 5.2.3 on 2025-08-20 03:04

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconmodel',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount percentage applied to retail price (0–100).', max_digits=5),
        ),
        migrations.AlterField(
            model_name='airconmodel',
            name='is_inverter',
            field=models.BooleanField(default=False, help_text='Uses inverter technology.'),
        ),
    ]
