# Generated by Django 5.2.3 on 2025-09-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0003_airconmodel_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconmodel',
            name='aircon_type',
            field=models.CharField(choices=[('window', 'Window Type'), ('split', 'Split Type'), ('floor_mounted', 'Floor Mounted'), ('cassette', 'Cassette Type'), ('portable', 'Portable'), ('centralized', 'Centralized')], default='window', max_length=30),
        ),
    ]
