# Generated by Django 4.2 on 2024-01-15

from decimal import Decimal

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0001_initial'),
        ('installations', '0004_alter_airconmodel_aircon_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_type', models.CharField(choices=[('repair', 'Repair'), ('replacement', 'Replacement'), ('parts', 'Parts Replacement'), ('inspection', 'Inspection')], default='repair', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('issue_description', models.TextField(help_text='Description of the issue/defect reported by customer')),
                ('customer_notes', models.TextField(blank=True, help_text='Additional notes from customer')),
                ('technician_assessment', models.TextField(blank=True, help_text="Technician's assessment of the issue")),
                ('is_valid_claim', models.BooleanField(default=True, help_text='Whether this is a valid warranty claim (not customer misuse, etc.)')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When the claim was reviewed/approved/rejected', null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Reason for rejection (if applicable)')),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Estimated cost of warranty repair/replacement', max_digits=10)),
                ('actual_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Actual cost incurred (if completed)', max_digits=10)),
                ('claim_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When the claim was submitted')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the warranty service was completed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Staff member who reviewed this claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_warranty_claims', to=settings.AUTH_USER_MODEL)),
                ('service', models.OneToOneField(blank=True, help_text='Service created to handle this warranty claim', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='warranty_claim', to='services.service')),
                ('unit', models.ForeignKey(help_text='Aircon unit this claim is for', on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='installations.airconunit')),
            ],
            options={
                'verbose_name': 'Warranty Claim',
                'verbose_name_plural': 'Warranty Claims',
                'ordering': ['-claim_date'],
            },
        ),
    ]
