# Generated by Django 5.2.3 on 2026-02-03 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0006_add_aircon_stall_integration'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconunit',
            name='outdoor_serial_number',
            field=models.CharField(blank=True, help_text='Outdoor unit serial number (for split-type units)', max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='airconunit',
            name='serial_number',
            field=models.CharField(help_text='Indoor unit serial number', max_length=100, unique=True),
        ),
    ]
