# Generated by Django 5.2.3 on 2026-02-10 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0007_add_outdoor_serial_number'),
    ]

    operations = [
        # Remove free_installation column if it exists
        migrations.RunSQL(
            sql='ALTER TABLE installations_airconinstallation DROP COLUMN IF EXISTS free_installation;',
            reverse_sql='ALTER TABLE installations_airconinstallation ADD COLUMN free_installation BOOLEAN NOT NULL DEFAULT FALSE;',
        ),
    ]
