# Generated by Django 5.2.3 on 2026-02-10 13:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0008_remove_free_installation_field'),
    ]

    operations = [
        # Drop labor_fee column if it exists (from previous schema drift)
        migrations.RunSQL(
            sql='ALTER TABLE installations_airconinstallation DROP COLUMN IF EXISTS labor_fee;',
            reverse_sql='',  # No reverse - this is cleaning up
        ),
        # Add installation_fee field
        migrations.AddField(
            model_name='airconinstallation',
            name='installation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Installation labor fee', max_digits=10),
        ),
    ]
