# Generated by Django 5.2.3 on 2026-02-10 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0009_add_installation_fee'),
    ]

    operations = [
        # Remove labor_is_free column if it exists (schema drift cleanup)
        migrations.RunSQL(
            sql='ALTER TABLE installations_airconinstallation DROP COLUMN IF EXISTS labor_is_free;',
            reverse_sql='',  # No reverse - this is cleaning up schema drift
        ),
    ]
