# Generated by Django 5.2.3 on 2026-02-10 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0011_remove_airconinstallation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='airconmodel',
            name='horsepower',
            field=models.CharField(choices=[('0.5', '0.5 HP (10-11 sqm)'), ('0.75', '0.75 HP (10-17 sqm)'), ('1.0', '1.0 HP (15-22 sqm)'), ('1.5', '1.5 HP (19-27 sqm)'), ('2.0', '2.0 HP (23-40 sqm)'), ('2.5', '2.5 HP (up to 54 sqm)')], default='1.0', help_text='Horsepower/capacity of the air conditioner', max_length=10),
        ),
    ]
