# Generated by Django 5.2.3 on 2026-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0017_replace_discount_with_promo_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airconmodel',
            name='horsepower',
            field=models.CharField(choices=[('0.5', '0.5 HP (10-11 sqm)'), ('0.75', '0.75 HP (10-17 sqm)'), ('0.8', '0.8 HP (12-18 sqm)'), ('1.0', '1.0 HP (15-22 sqm)'), ('1.5', '1.5 HP (19-27 sqm)'), ('2.0', '2.0 HP (23-40 sqm)'), ('2.5', '2.5 HP (up to 54 sqm)'), ('3.0', '3.0 HP (45-65 sqm)'), ('4.0', '4.0 HP (60-85 sqm)'), ('5.0', '5.0 HP (80-110 sqm)'), ('7.5', '7.5 HP (110-160 sqm)'), ('10.0', '10.0 HP (160-220 sqm)')], default='1.0', help_text='Horsepower/capacity of the air conditioner', max_length=10),
        ),
    ]
