# Generated by Django 5.2.3 on 2026-03-10 03:46
# Modified to only update state - column already exists in DB

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0019_airconunit_compressor_warranty_months'),
    ]

    operations = [
        # Add the column to the DB if it doesn't exist (fresh setup),
        # and always register it in Django's state.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='airconunit',
                    name='compressor_warranty_months',
                    field=models.PositiveIntegerField(
                        blank=True,
                        help_text='Compressor warranty duration in months (if different from parts warranty)',
                        null=True,
                    ),
                ),
            ],
            database_operations=[
                migrations.RunSQL(
                    sql="""
                    DO $$
                    BEGIN
                        IF NOT EXISTS (
                            SELECT 1 FROM information_schema.columns
                            WHERE table_name = 'installations_airconunit'
                            AND column_name = 'compressor_warranty_months'
                        ) THEN
                            ALTER TABLE installations_airconunit
                                ADD COLUMN compressor_warranty_months integer NULL;
                        END IF;
                    END $$;
                    """,
                    reverse_sql="ALTER TABLE installations_airconunit DROP COLUMN IF EXISTS compressor_warranty_months;",
                ),
            ],
        ),
    ]
