# Generated by Django 5.2.3 on 2026-03-10 03:46
# Modified to only update state - column already exists in DB

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0019_airconunit_compressor_warranty_months'),
    ]

    operations = [
        # Column already exists in DB (was made nullable in 0019)
        # Only update Django's state to recognize the field
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='airconunit',
                    name='compressor_warranty_months',
                    field=models.PositiveIntegerField(
                        blank=True,
                        help_text='Compressor warranty duration in months (if different from parts warranty)',
                        null=True
                    ),
                ),
            ],
            database_operations=[
                # No database operations needed - column already exists
            ],
        ),
    ]
