# Generated by Django 5.2.3 on 2026-03-10 03:49
# Modified to only update state - column already exists in DB

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0021_make_labor_warranty_nullable'),
    ]

    operations = [
        # Column already exists in DB (was made nullable in 0021)
        # Only update Django's state to recognize the field
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AddField(
                    model_name='airconunit',
                    name='labor_warranty_months',
                    field=models.PositiveIntegerField(
                        blank=True,
                        help_text='Labor warranty duration in months (overrides model default if set)',
                        null=True
                    ),
                ),
            ],
            database_operations=[
                # No database operations needed - column already exists
            ],
        ),
    ]
