# Generated by Django 5.2.3 on 2026-01-27 03:07

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('clock_in', models.DateTimeField(blank=True, null=True)),
                ('clock_out', models.DateTimeField(blank=True, null=True)),
                ('attendance_type', models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day'), ('PARTIAL', 'Partial Hours'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave')], default='PENDING', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total clock hours (clock_out - clock_in)', max_digits=5)),
                ('break_hours', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Unpaid break hours (auto-deducted)', max_digits=5)),
                ('paid_hours', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hours counted for payroll', max_digits=5)),
                ('is_late', models.BooleanField(default=False)),
                ('late_minutes', models.PositiveIntegerField(default=0, help_text='Minutes late beyond grace period')),
                ('late_penalty_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Penalty: ₱2 per minute late', max_digits=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_attendances', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Attendance',
                'verbose_name_plural': 'Daily Attendances',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_0ead4a_idx'), models.Index(fields=['date'], name='attendance__date_370344_idx'), models.Index(fields=['status'], name='attendance__status_ac56c5_idx'), models.Index(fields=['attendance_type'], name='attendance__attenda_76efa4_idx')],
                'unique_together': {('employee', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('sick_leave_total', models.PositiveIntegerField(default=5, help_text='Total sick leave days allocated for the year')),
                ('sick_leave_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Sick leave days used (supports half-days)', max_digits=5)),
                ('emergency_leave_total', models.PositiveIntegerField(default=5, help_text='Total emergency leave days allocated for the year')),
                ('emergency_leave_used', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Emergency leave days used (supports half-days)', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Balance',
                'verbose_name_plural': 'Leave Balances',
                'ordering': ['-year', 'employee'],
                'indexes': [models.Index(fields=['employee', 'year'], name='attendance__employe_785b64_idx'), models.Index(fields=['year'], name='attendance__year_9dca27_idx')],
                'unique_together': {('employee', 'year')},
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave')], max_length=20)),
                ('date', models.DateField()),
                ('is_half_day', models.BooleanField(default=False, help_text='True if half-day leave (0.5 days), False for full-day (1.0 days)')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_leave_requests', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Leave Request',
                'verbose_name_plural': 'Leave Requests',
                'ordering': ['-date', 'employee'],
                'indexes': [models.Index(fields=['employee', 'date'], name='attendance__employe_d0e52f_idx'), models.Index(fields=['date'], name='attendance__date_1a3c68_idx'), models.Index(fields=['status'], name='attendance__status_6e3dfd_idx'), models.Index(fields=['leave_type'], name='attendance__leave_t_f68c1a_idx')],
            },
        ),
    ]
