# Generated by Django 5.2.3 on 2026-01-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='auto_closed',
            field=models.BooleanField(default=False, help_text='True if the attendance was auto-closed due to missing clock_out'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='consecutive_absences',
            field=models.PositiveIntegerField(default=0, help_text='Counts consecutive absences without approved leave for AWOL monitoring'),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_type',
            field=models.CharField(choices=[('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day'), ('PARTIAL', 'Partial Hours'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('INVALID', 'Invalid')], default='PENDING', max_length=20),
        ),
    ]
