# Generated by Django 5.2.3 on 2026-01-28 02:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_dailyattendance_auto_closed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyattendance',
            name='auto_close_warning_count',
            field=models.PositiveIntegerField(default=0, help_text='Cumulative count of auto-close warnings (for repeated violations)'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='is_awol',
            field=models.BooleanField(default=False, help_text='True if employee has 3+ consecutive absences (AWOL flag)'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='missing_uniform_pants',
            field=models.BooleanField(default=False, help_text='Missing or incomplete pants/uniform bottom'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='missing_uniform_shirt',
            field=models.BooleanField(default=False, help_text='Missing or incomplete shirt/uniform top'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='missing_uniform_shoes',
            field=models.BooleanField(default=False, help_text='Missing or incomplete shoes/footwear'),
        ),
        migrations.AddField(
            model_name='dailyattendance',
            name='uniform_penalty_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total uniform penalty: ₱50 per missing item', max_digits=10),
        ),
    ]
