# Generated by Django 5.2.3 on 2026-01-28 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_dailyattendance_auto_close_warning_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaverequest',
            name='shift_period',
            field=models.CharField(choices=[('AM', 'Morning'), ('PM', 'Afternoon'), ('FULL', 'Full Day')], default='FULL', help_text='AM, PM, or FULL day - determines which shift the leave applies to', max_length=10),
        ),
    ]
