# Generated by Django 5.2.3 on 2026-01-29 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0004_leaverequest_shift_period'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offense_type', models.CharField(choices=[('AWOL', 'Absent Without Leave'), ('LATE', 'Late Arrival'), ('CURFEW', 'Curfew Violation'), ('OTHER', 'Other Violation')], max_length=20)),
                ('severity_level', models.CharField(choices=[('WARNING', '1st Offense - Warning'), ('SUSPENSION', '2nd Offense - Suspension'), ('TERMINATION', '3rd Offense - Termination')], max_length=20)),
                ('date', models.DateField(help_text='Date of the offense')),
                ('description', models.TextField(help_text='Detailed description of the offense')),
                ('penalty_days', models.IntegerField(default=0, help_text='Number of suspension days (for 2nd offense)')),
                ('suspension_start_date', models.DateField(blank=True, help_text='Start date of suspension (for 2nd offense)', null=True)),
                ('suspension_end_date', models.DateField(blank=True, help_text='End date of suspension (for 2nd offense)', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offenses_created', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['employee', '-date'], name='attendance__employe_568a48_idx'), models.Index(fields=['offense_type'], name='attendance__offense_3e4028_idx'), models.Index(fields=['severity_level'], name='attendance__severit_3e41c4_idx')],
            },
        ),
    ]
