# Generated by Django 5.2.3 on 2026-02-13 14:13

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_overtimerequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='break_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Unpaid break hours (auto-deducted from overlap with break periods)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='paid_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Hours counted for payroll (excludes early clock-in and break time)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailyattendance',
            name='total_hours',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total clock hours (actual clock_out - clock_in for reference only, NOT paid hours)', max_digits=5),
        ),
        migrations.CreateModel(
            name='HalfDaySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='half_day_schedules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'half_day_schedules',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date'], name='half_day_sc_date_cc7e64_idx'), models.Index(fields=['is_deleted'], name='half_day_sc_is_dele_772ec4_idx')],
            },
        ),
    ]
