# Generated by Django 5.2.3 on 2026-03-02 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_add_start_end_date_to_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaverequest',
            name='is_half_day',
            field=models.BooleanField(default=False, help_text='True if half-day leave (0.5 days), False for full-day (1.0 days). Only applicable for single-day leaves.'),
        ),
    ]
