# Generated by Django 5.2.3 on 2026-03-03 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_soft_delete_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_type',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day'), ('PARTIAL', 'Partial Hours'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('INVALID', 'Invalid')], default='PENDING', max_length=20),
        ),
    ]
