# Generated by Django 5.2.3 on 2026-03-07 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_add_pending_to_attendance_type_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyattendance',
            name='attendance_type',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('FULL_DAY', 'Full Day'), ('HALF_DAY', 'Half Day'), ('PARTIAL', 'Partial Hours'), ('ABSENT', 'Absent'), ('LEAVE', 'On Leave'), ('SHOP_CLOSED', 'Shop Closed'), ('INVALID', 'Invalid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='leave_type',
            field=models.CharField(choices=[('SICK', 'Sick Leave'), ('EMERGENCY', 'Emergency Leave'), ('SPECIAL', 'Special Leave')], max_length=20),
        ),
    ]
