# Generated by Django 5.2.3 on 2026-03-08 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0013_halfdayschedule_schedule_type'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='halfdayschedule',
            new_name='half_day_sc_schedul_fa530e_idx',
            old_name='half_day_sc_schedul_idx',
        ),
    ]
