# Generated by Django 5.2.3 on 2025-08-06 06:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_add_partial_unique_index'),
        ('sales', '0008_salestransaction_change_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChequeCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_collected', models.DateField()),
                ('issued_by', models.CharField(max_length=100)),
                ('billing_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cheque_number', models.CharField(max_length=50)),
                ('cheque_date', models.DateField(help_text='Date written on the cheque (can be post-dated).')),
                ('bank_name', models.CharField(help_text='Name of the bank that issued the cheque.', max_length=100)),
                ('or_number', models.CharField(blank=True, max_length=50, null=True)),
                ('collection_type', models.CharField(choices=[('picked_up', 'Picked Up by Staff'), ('client_delivered', 'Delivered by Client')], default='client_delivered', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('deposited', 'Deposited'), ('encashed', 'Encashed'), ('returned', 'Returned'), ('bounced', 'Bounced'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheque_collections', to='clients.client')),
                ('collected_by', models.ForeignKey(blank=True, help_text="Only required if Collection Type is 'Picked Up by Staff'.", limit_choices_to={'role__in': ['manager', 'clerk', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collected_cheques', to=settings.AUTH_USER_MODEL)),
                ('sales_transaction', models.ForeignKey(blank=True, help_text='Linked sales transaction, if available.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cheque_collections', to='sales.salestransaction')),
            ],
            options={
                'ordering': ['-date_collected'],
                'indexes': [models.Index(fields=['date_collected'], name='receivables_date_co_25c100_idx'), models.Index(fields=['cheque_number'], name='receivables_cheque__7c7f56_idx'), models.Index(fields=['collection_type'], name='receivables_collect_bfbf83_idx'), models.Index(fields=['cheque_date'], name='receivables_cheque__c12eb8_idx'), models.Index(fields=['sales_transaction'], name='receivables_sales_t_d47637_idx')],
            },
        ),
    ]
