# Generated by Django 5.2.3 on 2025-08-06 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequecollection',
            name='cheque_date',
            field=models.DateTimeField(help_text='Date written on the cheque (can be post-dated).'),
        ),
        migrations.AlterField(
            model_name='chequecollection',
            name='date_collected',
            field=models.DateTimeField(),
        ),
    ]
