# Generated by Django 5.2.3 on 2025-08-07 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0002_alter_chequecollection_cheque_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequecollection',
            name='bank_name',
            field=models.CharField(choices=[('BPI', 'BPI'), ('BDO', 'BDO'), ('Metrobank', 'Metrobank'), ('Landbank', 'Landbank'), ('Security Bank', 'Security Bank'), ('UnionBank', 'UnionBank'), ('RCBC', 'RCBC'), ('PNB', 'PNB'), ('EastWestBank', 'EastWest Bank'), ('ChinaBank', 'China Bank'), ('Maybank Philippines', 'Maybank Philippines')], help_text='Name of the bank that issued the cheque.', max_length=100),
        ),
    ]
