# Generated by Django 5.2.3 on 2025-08-08 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0003_alter_chequecollection_bank_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chequecollection',
            name='deposit_bank',
            field=models.CharField(blank=True, choices=[('BPI', 'BPI'), ('BDO', 'BDO'), ('Metrobank', 'Metrobank'), ('Landbank', 'Landbank'), ('Security Bank', 'Security Bank'), ('UnionBank', 'UnionBank'), ('RCBC', 'RCBC'), ('PNB', 'PNB'), ('EastWestBank', 'EastWest Bank'), ('ChinaBank', 'China Bank'), ('Maybank Philippines', 'Maybank Philippines')], help_text='Name of the bank where the cheque will be deposited or encashed.', max_length=100, null=True),
        ),
    ]
