# Generated by Django 5.2.3 on 2026-04-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receivables', '0004_chequecollection_deposit_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chequecollection',
            name='bank_name',
            field=models.CharField(choices=[('BPI', 'BPI'), ('BDO', 'BDO'), ('Metrobank', 'Metrobank'), ('Landbank', 'Landbank'), ('Security Bank', 'Security Bank'), ('UnionBank', 'UnionBank'), ('RCBC', 'RCBC'), ('PNB', 'PNB'), ('EastWestBank', 'EastWest Bank'), ('ChinaBank', 'China Bank'), ('Maybank Philippines', 'Maybank Philippines'), ('Porac Bank', 'Porac Bank')], help_text='Name of the bank that issued the cheque.', max_length=100),
        ),
        migrations.AlterField(
            model_name='chequecollection',
            name='deposit_bank',
            field=models.CharField(blank=True, choices=[('BPI', 'BPI'), ('BDO', 'BDO'), ('Metrobank', 'Metrobank'), ('Landbank', 'Landbank'), ('Security Bank', 'Security Bank'), ('UnionBank', 'UnionBank'), ('RCBC', 'RCBC'), ('PNB', 'PNB'), ('EastWestBank', 'EastWest Bank'), ('ChinaBank', 'China Bank'), ('Maybank Philippines', 'Maybank Philippines'), ('Porac Bank', 'Porac Bank')], help_text='Name of the bank where the cheque will be deposited or encashed.', max_length=100, null=True),
        ),
    ]
