# Generated by Django 5.2.3 on 2025-06-25 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_rename_price_item_srp'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='stall',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='inventory.stall'),
            preserve_default=False,
        ),
    ]
