# Generated by Django 5.2.3 on 2025-06-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_salestransaction_stall'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
