# Generated by Django 5.2.3 on 2025-07-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_salestransaction_receipt_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='salesitem',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='receipt_number',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='sales_clerk',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='total_payment',
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='manual_receipt_number',
            field=models.CharField(blank=True, help_text='Official receipt number provided by the customer', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('credit', 'Credit'), ('debit', 'Debit'), ('cheque', 'Cheque')], default=None, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='printed_receipt_number',
            field=models.CharField(blank=True, help_text="Receipt number from the system's POS receipt printing", max_length=100, null=True),
        ),
    ]
