# Generated by Django 5.2.3 on 2025-07-10 07:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0023_stocktransfer_used_for'),
        ('sales', '0004_remove_salesitem_final_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesitem',
            name='discount_amount',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='payment_type',
        ),
        migrations.RemoveField(
            model_name='salestransaction',
            name='printed_receipt_number',
        ),
        migrations.AddField(
            model_name='salesitem',
            name='description',
            field=models.CharField(blank=True, help_text='For non-inventory charges like labor fees.', max_length=255),
        ),
        migrations.AddField(
            model_name='salesitem',
            name='final_price_per_unit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Actual unit price charged (auto-set from item if not provided)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid')], default='unpaid', max_length=10),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='system_receipt_number',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='salestransaction',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='item',
            field=models.ForeignKey(blank=True, help_text='Leave blank for manual/labor/service line.', null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.item'),
        ),
        migrations.AlterField(
            model_name='salesitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='manual_receipt_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='SalesPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('gcash', 'GCash'), ('credit', 'Credit'), ('debit', 'Debit'), ('cheque', 'Cheque')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='sales.salestransaction')),
            ],
        ),
    ]
