# Generated by Django 5.2.3 on 2025-07-14 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_salestransaction_sales_clerk'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salestransaction',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('paid', 'Paid'), ('voided', 'Voided')], default='unpaid', max_length=10),
        ),
    ]
