# Generated by Django 5.2.3 on 2025-07-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_salestransaction_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
