# Generated by Django 5.2.3 on 2025-07-28 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installations', '0001_initial'),
        ('sales', '0008_salestransaction_change_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesitem',
            name='aircon_unit',
            field=models.ForeignKey(blank=True, help_text='Link to sold aircon unit (if applicable). Overrides item and description.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='installations.airconunit'),
        ),
    ]
