# Generated by Django 5.2.3 on 2025-12-03 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_discounts'),
        ('sales', '0008_salestransaction_change_amount'),
    ]

    operations = [
    ]
