# Generated by Django 5.2.3 on 2026-03-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_add_transaction_type_and_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salestransaction',
            old_name='order_discount_rate',
            new_name='order_discount',
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='order_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Order-level discount in peso amount.', max_digits=10),
        ),
    ]
