# Generated by Django 5.2.3

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_rename_discount_to_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='transaction_date',
            field=models.DateField(
                blank=True,
                help_text='The date this transaction occurred. Defaults to creation date.',
                null=True,
            ),
        ),
    ]
