# Generated by Django 5.2.3 on 2026-03-25 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0017_backfill_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='salestransaction',
            name='receipt_book',
            field=models.CharField(blank=True, help_text="Receipt book number (e.g. '1', '2'). Same SI/OR # can exist in different books.", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='salestransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('replacement', 'Replacement'), ('pull_out', 'Pull Out'), ('service', 'Service')], default='sale', max_length=20),
        ),
    ]
