# Generated by Django 5.2.3 on 2026-04-03 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0018_add_receipt_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salestransaction',
            name='transaction_type',
            field=models.CharField(choices=[('sale', 'Sale'), ('replacement', 'Replacement'), ('pull_out', 'Pull Out'), ('service', 'Service'), ('asset_sale', 'Asset Sale')], default='sale', max_length=20),
        ),
    ]
